// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_2_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        in1_V_TVALID,
        out0_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID,
        in1_V_TDATA,
        in1_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   in1_V_TVALID;
input   out0_V_TREADY;
input  [127:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out0_V_TDATA;
output   out0_V_TVALID;
input  [127:0] in1_V_TDATA;
output   in1_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out0_V_TVALID;
reg in1_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
wire   [0:0] icmp_ln249_fu_530_p2;
wire   [0:0] icmp_ln253_fu_542_p2;
reg    ap_predicate_op27_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg   [0:0] icmp_ln249_reg_3593;
reg   [0:0] icmp_ln249_reg_3593_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
wire    ap_CS_iter4_fsm_state5;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [5:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [5:0] p_ZL7threshs_1_q0;
wire   [5:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [5:0] p_ZL7threshs_2_q0;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
reg    in1_V_TDATA_blk_n;
reg   [31:0] nf_3_reg_3588;
wire   [0:0] icmp_ln249_reg_3593_pp0_iter0_reg;
reg   [0:0] icmp_ln249_reg_3593_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_3593_pp0_iter2_reg;
wire   [1:0] local_temp_V_fu_553_p1;
reg  signed [1:0] local_temp_V_reg_3600;
reg  signed [1:0] local_temp_V_1_reg_3605;
reg  signed [1:0] local_temp_V_2_reg_3610;
reg  signed [1:0] local_temp_V_3_reg_3615;
reg  signed [1:0] local_temp_V_4_reg_3620;
reg  signed [1:0] local_temp_V_5_reg_3625;
reg  signed [1:0] local_temp_V_6_reg_3630;
reg  signed [1:0] local_temp_V_7_reg_3635;
reg  signed [1:0] local_temp_V_8_reg_3640;
reg  signed [1:0] local_temp_V_9_reg_3645;
reg  signed [1:0] local_temp_V_10_reg_3650;
reg  signed [1:0] local_temp_V_11_reg_3655;
reg  signed [1:0] local_temp_V_12_reg_3660;
reg  signed [1:0] local_temp_V_13_reg_3665;
reg  signed [1:0] local_temp_V_14_reg_3670;
reg  signed [1:0] local_temp_V_15_reg_3675;
reg  signed [1:0] local_temp_V_16_reg_3680;
reg  signed [1:0] local_temp_V_17_reg_3685;
reg  signed [1:0] local_temp_V_18_reg_3690;
reg  signed [1:0] local_temp_V_19_reg_3695;
reg  signed [1:0] local_temp_V_20_reg_3700;
reg  signed [1:0] local_temp_V_21_reg_3705;
reg  signed [1:0] local_temp_V_22_reg_3710;
reg  signed [1:0] local_temp_V_23_reg_3715;
reg  signed [1:0] local_temp_V_24_reg_3720;
reg  signed [1:0] local_temp_V_25_reg_3725;
reg  signed [1:0] local_temp_V_26_reg_3730;
reg  signed [1:0] local_temp_V_27_reg_3735;
reg  signed [1:0] local_temp_V_28_reg_3740;
reg  signed [1:0] local_temp_V_29_reg_3745;
reg  signed [1:0] local_temp_V_30_reg_3750;
reg  signed [1:0] local_temp_V_31_reg_3755;
reg  signed [1:0] local_temp_V_32_reg_3760;
reg  signed [1:0] local_temp_V_33_reg_3765;
reg  signed [1:0] local_temp_V_34_reg_3770;
reg  signed [1:0] local_temp_V_35_reg_3775;
reg  signed [1:0] local_temp_V_36_reg_3780;
reg  signed [1:0] local_temp_V_37_reg_3785;
reg  signed [1:0] local_temp_V_38_reg_3790;
reg  signed [1:0] local_temp_V_39_reg_3795;
reg  signed [1:0] local_temp_V_40_reg_3800;
reg  signed [1:0] local_temp_V_41_reg_3805;
reg  signed [1:0] local_temp_V_42_reg_3810;
reg  signed [1:0] local_temp_V_43_reg_3815;
reg  signed [1:0] local_temp_V_44_reg_3820;
reg  signed [1:0] local_temp_V_45_reg_3825;
reg  signed [1:0] local_temp_V_46_reg_3830;
reg  signed [1:0] local_temp_V_47_reg_3835;
reg  signed [1:0] local_temp_V_48_reg_3840;
reg  signed [1:0] local_temp_V_49_reg_3845;
reg  signed [1:0] local_temp_V_50_reg_3850;
reg  signed [1:0] local_temp_V_51_reg_3855;
reg  signed [1:0] local_temp_V_52_reg_3860;
reg  signed [1:0] local_temp_V_53_reg_3865;
reg  signed [1:0] local_temp_V_54_reg_3870;
reg  signed [1:0] local_temp_V_55_reg_3875;
reg  signed [1:0] local_temp_V_56_reg_3880;
reg  signed [1:0] local_temp_V_57_reg_3885;
reg  signed [1:0] local_temp_V_58_reg_3890;
reg  signed [1:0] local_temp_V_59_reg_3895;
reg  signed [1:0] local_temp_V_60_reg_3900;
reg  signed [1:0] local_temp_V_61_reg_3905;
reg  signed [1:0] local_temp_V_62_reg_3910;
reg  signed [1:0] local_temp_V_63_reg_3915;
wire   [5:0] add_ln840_2_fu_2962_p2;
reg   [5:0] add_ln840_2_reg_3920;
wire   [5:0] add_ln840_5_fu_2988_p2;
reg   [5:0] add_ln840_5_reg_3925;
wire   [5:0] add_ln840_9_fu_3014_p2;
reg   [5:0] add_ln840_9_reg_3930;
wire   [5:0] add_ln840_12_fu_3040_p2;
reg   [5:0] add_ln840_12_reg_3935;
wire   [5:0] add_ln840_17_fu_3066_p2;
reg   [5:0] add_ln840_17_reg_3940;
wire   [5:0] add_ln840_20_fu_3092_p2;
reg   [5:0] add_ln840_20_reg_3945;
wire   [5:0] add_ln840_24_fu_3118_p2;
reg   [5:0] add_ln840_24_reg_3950;
wire   [5:0] add_ln840_27_fu_3144_p2;
reg   [5:0] add_ln840_27_reg_3955;
wire   [5:0] add_ln840_33_fu_3170_p2;
reg   [5:0] add_ln840_33_reg_3960;
wire   [5:0] add_ln840_36_fu_3196_p2;
reg   [5:0] add_ln840_36_reg_3965;
wire   [5:0] add_ln840_40_fu_3222_p2;
reg   [5:0] add_ln840_40_reg_3970;
wire   [5:0] add_ln840_43_fu_3248_p2;
reg   [5:0] add_ln840_43_reg_3975;
wire   [5:0] add_ln840_48_fu_3274_p2;
reg   [5:0] add_ln840_48_reg_3980;
wire   [5:0] add_ln840_51_fu_3300_p2;
reg   [5:0] add_ln840_51_reg_3985;
wire   [5:0] add_ln840_55_fu_3326_p2;
reg   [5:0] add_ln840_55_reg_3990;
wire   [5:0] add_ln840_58_fu_3352_p2;
reg   [5:0] add_ln840_58_reg_3995;
wire   [6:0] add_ln840_14_fu_3388_p2;
reg   [6:0] add_ln840_14_reg_4015;
wire   [6:0] add_ln840_29_fu_3418_p2;
reg   [6:0] add_ln840_29_reg_4020;
wire   [6:0] add_ln840_37_fu_3430_p2;
reg   [6:0] add_ln840_37_reg_4025;
wire   [6:0] add_ln840_44_fu_3442_p2;
reg   [6:0] add_ln840_44_reg_4030;
wire   [6:0] add_ln840_60_fu_3472_p2;
reg   [6:0] add_ln840_60_reg_4035;
reg   [5:0] p_ZL7threshs_0_load_reg_4040;
reg   [5:0] p_ZL7threshs_0_load_reg_4040_pp0_iter3_reg;
reg   [5:0] p_ZL7threshs_1_load_reg_4045;
reg   [5:0] p_ZL7threshs_1_load_reg_4045_pp0_iter3_reg;
reg   [5:0] p_ZL7threshs_2_load_reg_4050;
reg   [5:0] p_ZL7threshs_2_load_reg_4050_pp0_iter3_reg;
wire   [6:0] add_ln840_62_fu_3491_p2;
reg   [6:0] add_ln840_62_reg_4055;
wire   [63:0] idxprom2_i_fu_3358_p1;
reg   [31:0] nf_1_fu_444;
wire   [31:0] nf_4_fu_1199_p3;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_nf_3;
reg   [6:0] i_fu_448;
wire   [6:0] i_2_fu_536_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [127:0] p_Val2_s_fu_452;
wire   [31:0] nf_fu_1187_p2;
wire   [0:0] icmp_ln302_fu_1193_p2;
wire   [1:0] r_V_fu_1220_p1;
wire   [1:0] ret_V_fu_1231_p0;
wire  signed [3:0] ret_V_fu_1231_p2;
wire   [1:0] r_V_1_fu_1241_p4;
wire   [1:0] ret_V_1_fu_1258_p0;
wire  signed [3:0] ret_V_1_fu_1258_p2;
wire   [1:0] r_V_2_fu_1268_p4;
wire   [1:0] ret_V_2_fu_1285_p0;
wire  signed [3:0] ret_V_2_fu_1285_p2;
wire   [1:0] r_V_3_fu_1295_p4;
wire   [1:0] ret_V_3_fu_1312_p0;
wire  signed [3:0] ret_V_3_fu_1312_p2;
wire   [1:0] r_V_4_fu_1322_p4;
wire   [1:0] ret_V_4_fu_1339_p0;
wire  signed [3:0] ret_V_4_fu_1339_p2;
wire   [1:0] r_V_5_fu_1349_p4;
wire   [1:0] ret_V_5_fu_1366_p0;
wire  signed [3:0] ret_V_5_fu_1366_p2;
wire   [1:0] r_V_6_fu_1376_p4;
wire   [1:0] ret_V_6_fu_1393_p0;
wire  signed [3:0] ret_V_6_fu_1393_p2;
wire   [1:0] r_V_7_fu_1403_p4;
wire   [1:0] ret_V_7_fu_1420_p0;
wire  signed [3:0] ret_V_7_fu_1420_p2;
wire   [1:0] r_V_8_fu_1430_p4;
wire   [1:0] ret_V_8_fu_1447_p0;
wire  signed [3:0] ret_V_8_fu_1447_p2;
wire   [1:0] r_V_9_fu_1457_p4;
wire   [1:0] ret_V_9_fu_1474_p0;
wire  signed [3:0] ret_V_9_fu_1474_p2;
wire   [1:0] r_V_10_fu_1484_p4;
wire   [1:0] ret_V_10_fu_1501_p0;
wire  signed [3:0] ret_V_10_fu_1501_p2;
wire   [1:0] r_V_11_fu_1511_p4;
wire   [1:0] ret_V_11_fu_1528_p0;
wire  signed [3:0] ret_V_11_fu_1528_p2;
wire   [1:0] r_V_12_fu_1538_p4;
wire   [1:0] ret_V_12_fu_1555_p0;
wire  signed [3:0] ret_V_12_fu_1555_p2;
wire   [1:0] r_V_13_fu_1565_p4;
wire   [1:0] ret_V_13_fu_1582_p0;
wire  signed [3:0] ret_V_13_fu_1582_p2;
wire   [1:0] r_V_14_fu_1592_p4;
wire   [1:0] ret_V_14_fu_1609_p0;
wire  signed [3:0] ret_V_14_fu_1609_p2;
wire   [1:0] r_V_15_fu_1619_p4;
wire   [1:0] ret_V_15_fu_1636_p0;
wire  signed [3:0] ret_V_15_fu_1636_p2;
wire   [1:0] r_V_16_fu_1646_p4;
wire   [1:0] ret_V_16_fu_1663_p0;
wire  signed [3:0] ret_V_16_fu_1663_p2;
wire   [1:0] r_V_17_fu_1673_p4;
wire   [1:0] ret_V_17_fu_1690_p0;
wire  signed [3:0] ret_V_17_fu_1690_p2;
wire   [1:0] r_V_18_fu_1700_p4;
wire   [1:0] ret_V_18_fu_1717_p0;
wire  signed [3:0] ret_V_18_fu_1717_p2;
wire   [1:0] r_V_19_fu_1727_p4;
wire   [1:0] ret_V_19_fu_1744_p0;
wire  signed [3:0] ret_V_19_fu_1744_p2;
wire   [1:0] r_V_20_fu_1754_p4;
wire   [1:0] ret_V_20_fu_1771_p0;
wire  signed [3:0] ret_V_20_fu_1771_p2;
wire   [1:0] r_V_21_fu_1781_p4;
wire   [1:0] ret_V_21_fu_1798_p0;
wire  signed [3:0] ret_V_21_fu_1798_p2;
wire   [1:0] r_V_22_fu_1808_p4;
wire   [1:0] ret_V_22_fu_1825_p0;
wire  signed [3:0] ret_V_22_fu_1825_p2;
wire   [1:0] r_V_23_fu_1835_p4;
wire   [1:0] ret_V_23_fu_1852_p0;
wire  signed [3:0] ret_V_23_fu_1852_p2;
wire   [1:0] r_V_24_fu_1862_p4;
wire   [1:0] ret_V_24_fu_1879_p0;
wire  signed [3:0] ret_V_24_fu_1879_p2;
wire   [1:0] r_V_25_fu_1889_p4;
wire   [1:0] ret_V_25_fu_1906_p0;
wire  signed [3:0] ret_V_25_fu_1906_p2;
wire   [1:0] r_V_26_fu_1916_p4;
wire   [1:0] ret_V_26_fu_1933_p0;
wire  signed [3:0] ret_V_26_fu_1933_p2;
wire   [1:0] r_V_27_fu_1943_p4;
wire   [1:0] ret_V_27_fu_1960_p0;
wire  signed [3:0] ret_V_27_fu_1960_p2;
wire   [1:0] r_V_28_fu_1970_p4;
wire   [1:0] ret_V_28_fu_1987_p0;
wire  signed [3:0] ret_V_28_fu_1987_p2;
wire   [1:0] r_V_29_fu_1997_p4;
wire   [1:0] ret_V_29_fu_2014_p0;
wire  signed [3:0] ret_V_29_fu_2014_p2;
wire   [1:0] r_V_30_fu_2024_p4;
wire   [1:0] ret_V_30_fu_2041_p0;
wire  signed [3:0] ret_V_30_fu_2041_p2;
wire   [1:0] r_V_31_fu_2051_p4;
wire   [1:0] ret_V_31_fu_2068_p0;
wire  signed [3:0] ret_V_31_fu_2068_p2;
wire   [1:0] r_V_32_fu_2078_p4;
wire   [1:0] ret_V_32_fu_2095_p0;
wire  signed [3:0] ret_V_32_fu_2095_p2;
wire   [1:0] r_V_33_fu_2105_p4;
wire   [1:0] ret_V_33_fu_2122_p0;
wire  signed [3:0] ret_V_33_fu_2122_p2;
wire   [1:0] r_V_34_fu_2132_p4;
wire   [1:0] ret_V_34_fu_2149_p0;
wire  signed [3:0] ret_V_34_fu_2149_p2;
wire   [1:0] r_V_35_fu_2159_p4;
wire   [1:0] ret_V_35_fu_2176_p0;
wire  signed [3:0] ret_V_35_fu_2176_p2;
wire   [1:0] r_V_36_fu_2186_p4;
wire   [1:0] ret_V_36_fu_2203_p0;
wire  signed [3:0] ret_V_36_fu_2203_p2;
wire   [1:0] r_V_37_fu_2213_p4;
wire   [1:0] ret_V_37_fu_2230_p0;
wire  signed [3:0] ret_V_37_fu_2230_p2;
wire   [1:0] r_V_38_fu_2240_p4;
wire   [1:0] ret_V_38_fu_2257_p0;
wire  signed [3:0] ret_V_38_fu_2257_p2;
wire   [1:0] r_V_39_fu_2267_p4;
wire   [1:0] ret_V_39_fu_2284_p0;
wire  signed [3:0] ret_V_39_fu_2284_p2;
wire   [1:0] r_V_40_fu_2294_p4;
wire   [1:0] ret_V_40_fu_2311_p0;
wire  signed [3:0] ret_V_40_fu_2311_p2;
wire   [1:0] r_V_41_fu_2321_p4;
wire   [1:0] ret_V_41_fu_2338_p0;
wire  signed [3:0] ret_V_41_fu_2338_p2;
wire   [1:0] r_V_42_fu_2348_p4;
wire   [1:0] ret_V_42_fu_2365_p0;
wire  signed [3:0] ret_V_42_fu_2365_p2;
wire   [1:0] r_V_43_fu_2375_p4;
wire   [1:0] ret_V_43_fu_2392_p0;
wire  signed [3:0] ret_V_43_fu_2392_p2;
wire   [1:0] r_V_44_fu_2402_p4;
wire   [1:0] ret_V_44_fu_2419_p0;
wire  signed [3:0] ret_V_44_fu_2419_p2;
wire   [1:0] r_V_45_fu_2429_p4;
wire   [1:0] ret_V_45_fu_2446_p0;
wire  signed [3:0] ret_V_45_fu_2446_p2;
wire   [1:0] r_V_46_fu_2456_p4;
wire   [1:0] ret_V_46_fu_2473_p0;
wire  signed [3:0] ret_V_46_fu_2473_p2;
wire   [1:0] r_V_47_fu_2483_p4;
wire   [1:0] ret_V_47_fu_2500_p0;
wire  signed [3:0] ret_V_47_fu_2500_p2;
wire   [1:0] r_V_48_fu_2510_p4;
wire   [1:0] ret_V_48_fu_2527_p0;
wire  signed [3:0] ret_V_48_fu_2527_p2;
wire   [1:0] r_V_49_fu_2537_p4;
wire   [1:0] ret_V_49_fu_2554_p0;
wire  signed [3:0] ret_V_49_fu_2554_p2;
wire   [1:0] r_V_50_fu_2564_p4;
wire   [1:0] ret_V_50_fu_2581_p0;
wire  signed [3:0] ret_V_50_fu_2581_p2;
wire   [1:0] r_V_51_fu_2591_p4;
wire   [1:0] ret_V_51_fu_2608_p0;
wire  signed [3:0] ret_V_51_fu_2608_p2;
wire   [1:0] r_V_52_fu_2618_p4;
wire   [1:0] ret_V_52_fu_2635_p0;
wire  signed [3:0] ret_V_52_fu_2635_p2;
wire   [1:0] r_V_53_fu_2645_p4;
wire   [1:0] ret_V_53_fu_2662_p0;
wire  signed [3:0] ret_V_53_fu_2662_p2;
wire   [1:0] r_V_54_fu_2672_p4;
wire   [1:0] ret_V_54_fu_2689_p0;
wire  signed [3:0] ret_V_54_fu_2689_p2;
wire   [1:0] r_V_55_fu_2699_p4;
wire   [1:0] ret_V_55_fu_2716_p0;
wire  signed [3:0] ret_V_55_fu_2716_p2;
wire   [1:0] r_V_56_fu_2726_p4;
wire   [1:0] ret_V_56_fu_2743_p0;
wire  signed [3:0] ret_V_56_fu_2743_p2;
wire   [1:0] r_V_57_fu_2753_p4;
wire   [1:0] ret_V_57_fu_2770_p0;
wire  signed [3:0] ret_V_57_fu_2770_p2;
wire   [1:0] r_V_58_fu_2780_p4;
wire   [1:0] ret_V_58_fu_2797_p0;
wire  signed [3:0] ret_V_58_fu_2797_p2;
wire   [1:0] r_V_59_fu_2807_p4;
wire   [1:0] ret_V_59_fu_2824_p0;
wire  signed [3:0] ret_V_59_fu_2824_p2;
wire   [1:0] r_V_60_fu_2834_p4;
wire   [1:0] ret_V_60_fu_2851_p0;
wire  signed [3:0] ret_V_60_fu_2851_p2;
wire   [1:0] r_V_61_fu_2861_p4;
wire   [1:0] ret_V_61_fu_2878_p0;
wire  signed [3:0] ret_V_61_fu_2878_p2;
wire   [1:0] r_V_62_fu_2888_p4;
wire   [1:0] ret_V_62_fu_2905_p0;
wire  signed [3:0] ret_V_62_fu_2905_p2;
wire   [1:0] r_V_63_fu_2915_p4;
wire   [1:0] ret_V_63_fu_2932_p0;
wire  signed [3:0] ret_V_63_fu_2932_p2;
wire  signed [4:0] sext_ln628_61_fu_2884_p1;
wire  signed [4:0] sext_ln628_62_fu_2911_p1;
wire   [4:0] add_ln840_fu_2942_p2;
wire  signed [4:0] sext_ln628_60_fu_2857_p1;
wire  signed [4:0] sext_ln628_59_fu_2830_p1;
wire   [4:0] add_ln840_1_fu_2952_p2;
wire  signed [5:0] sext_ln840_2_fu_2958_p1;
wire  signed [5:0] sext_ln840_1_fu_2948_p1;
wire  signed [4:0] sext_ln628_56_fu_2749_p1;
wire  signed [4:0] sext_ln628_55_fu_2722_p1;
wire   [4:0] add_ln840_3_fu_2968_p2;
wire  signed [4:0] sext_ln628_58_fu_2803_p1;
wire  signed [4:0] sext_ln628_57_fu_2776_p1;
wire   [4:0] add_ln840_4_fu_2978_p2;
wire  signed [5:0] sext_ln840_5_fu_2984_p1;
wire  signed [5:0] sext_ln840_4_fu_2974_p1;
wire  signed [4:0] sext_ln628_48_fu_2533_p1;
wire  signed [4:0] sext_ln628_47_fu_2506_p1;
wire   [4:0] add_ln840_7_fu_2994_p2;
wire  signed [4:0] sext_ln628_50_fu_2587_p1;
wire  signed [4:0] sext_ln628_49_fu_2560_p1;
wire   [4:0] add_ln840_8_fu_3004_p2;
wire  signed [5:0] sext_ln840_8_fu_3010_p1;
wire  signed [5:0] sext_ln840_7_fu_3000_p1;
wire  signed [4:0] sext_ln628_52_fu_2641_p1;
wire  signed [4:0] sext_ln628_51_fu_2614_p1;
wire   [4:0] add_ln840_10_fu_3020_p2;
wire  signed [4:0] sext_ln628_54_fu_2695_p1;
wire  signed [4:0] sext_ln628_53_fu_2668_p1;
wire   [4:0] add_ln840_11_fu_3030_p2;
wire  signed [5:0] sext_ln840_11_fu_3036_p1;
wire  signed [5:0] sext_ln840_10_fu_3026_p1;
wire  signed [4:0] sext_ln628_32_fu_2101_p1;
wire  signed [4:0] sext_ln628_31_fu_2074_p1;
wire   [4:0] add_ln840_15_fu_3046_p2;
wire  signed [4:0] sext_ln628_34_fu_2155_p1;
wire  signed [4:0] sext_ln628_33_fu_2128_p1;
wire   [4:0] add_ln840_16_fu_3056_p2;
wire  signed [5:0] sext_ln840_14_fu_3062_p1;
wire  signed [5:0] sext_ln840_13_fu_3052_p1;
wire  signed [4:0] sext_ln628_36_fu_2209_p1;
wire  signed [4:0] sext_ln628_35_fu_2182_p1;
wire   [4:0] add_ln840_18_fu_3072_p2;
wire  signed [4:0] sext_ln628_38_fu_2263_p1;
wire  signed [4:0] sext_ln628_37_fu_2236_p1;
wire   [4:0] add_ln840_19_fu_3082_p2;
wire  signed [5:0] sext_ln840_17_fu_3088_p1;
wire  signed [5:0] sext_ln840_16_fu_3078_p1;
wire  signed [4:0] sext_ln628_40_fu_2317_p1;
wire  signed [4:0] sext_ln628_39_fu_2290_p1;
wire   [4:0] add_ln840_22_fu_3098_p2;
wire  signed [4:0] sext_ln628_42_fu_2371_p1;
wire  signed [4:0] sext_ln628_41_fu_2344_p1;
wire   [4:0] add_ln840_23_fu_3108_p2;
wire  signed [5:0] sext_ln840_20_fu_3114_p1;
wire  signed [5:0] sext_ln840_19_fu_3104_p1;
wire  signed [4:0] sext_ln628_44_fu_2425_p1;
wire  signed [4:0] sext_ln628_43_fu_2398_p1;
wire   [4:0] add_ln840_25_fu_3124_p2;
wire  signed [4:0] sext_ln628_46_fu_2479_p1;
wire  signed [4:0] sext_ln628_45_fu_2452_p1;
wire   [4:0] add_ln840_26_fu_3134_p2;
wire  signed [5:0] sext_ln840_23_fu_3140_p1;
wire  signed [5:0] sext_ln840_22_fu_3130_p1;
wire  signed [4:0] sext_ln628_1_fu_1264_p1;
wire  signed [4:0] sext_ln628_2_fu_1291_p1;
wire   [4:0] add_ln840_31_fu_3150_p2;
wire  signed [4:0] sext_ln628_fu_1237_p1;
wire  signed [4:0] sext_ln628_4_fu_1345_p1;
wire   [4:0] add_ln840_32_fu_3160_p2;
wire  signed [5:0] sext_ln840_26_fu_3166_p1;
wire  signed [5:0] sext_ln840_25_fu_3156_p1;
wire  signed [4:0] sext_ln628_3_fu_1318_p1;
wire  signed [4:0] sext_ln628_6_fu_1399_p1;
wire   [4:0] add_ln840_34_fu_3176_p2;
wire  signed [4:0] sext_ln628_5_fu_1372_p1;
wire  signed [4:0] sext_ln628_8_fu_1453_p1;
wire   [4:0] add_ln840_35_fu_3186_p2;
wire  signed [5:0] sext_ln840_29_fu_3192_p1;
wire  signed [5:0] sext_ln840_28_fu_3182_p1;
wire  signed [4:0] sext_ln628_7_fu_1426_p1;
wire  signed [4:0] sext_ln628_10_fu_1507_p1;
wire   [4:0] add_ln840_38_fu_3202_p2;
wire  signed [4:0] sext_ln628_9_fu_1480_p1;
wire  signed [4:0] sext_ln628_12_fu_1561_p1;
wire   [4:0] add_ln840_39_fu_3212_p2;
wire  signed [5:0] sext_ln840_32_fu_3218_p1;
wire  signed [5:0] sext_ln840_31_fu_3208_p1;
wire  signed [4:0] sext_ln628_11_fu_1534_p1;
wire  signed [4:0] sext_ln628_14_fu_1615_p1;
wire   [4:0] add_ln840_41_fu_3228_p2;
wire  signed [4:0] sext_ln628_13_fu_1588_p1;
wire  signed [4:0] sext_ln628_16_fu_1669_p1;
wire   [4:0] add_ln840_42_fu_3238_p2;
wire  signed [5:0] sext_ln840_35_fu_3244_p1;
wire  signed [5:0] sext_ln840_34_fu_3234_p1;
wire  signed [4:0] sext_ln628_15_fu_1642_p1;
wire  signed [4:0] sext_ln628_18_fu_1723_p1;
wire   [4:0] add_ln840_46_fu_3254_p2;
wire  signed [4:0] sext_ln628_17_fu_1696_p1;
wire  signed [4:0] sext_ln628_20_fu_1777_p1;
wire   [4:0] add_ln840_47_fu_3264_p2;
wire  signed [5:0] sext_ln840_38_fu_3270_p1;
wire  signed [5:0] sext_ln840_37_fu_3260_p1;
wire  signed [4:0] sext_ln628_19_fu_1750_p1;
wire  signed [4:0] sext_ln628_22_fu_1831_p1;
wire   [4:0] add_ln840_49_fu_3280_p2;
wire  signed [4:0] sext_ln628_21_fu_1804_p1;
wire  signed [4:0] sext_ln628_24_fu_1885_p1;
wire   [4:0] add_ln840_50_fu_3290_p2;
wire  signed [5:0] sext_ln840_41_fu_3296_p1;
wire  signed [5:0] sext_ln840_40_fu_3286_p1;
wire  signed [4:0] sext_ln628_23_fu_1858_p1;
wire  signed [4:0] sext_ln628_26_fu_1939_p1;
wire   [4:0] add_ln840_53_fu_3306_p2;
wire  signed [4:0] sext_ln628_25_fu_1912_p1;
wire  signed [4:0] sext_ln628_28_fu_1993_p1;
wire   [4:0] add_ln840_54_fu_3316_p2;
wire  signed [5:0] sext_ln840_44_fu_3322_p1;
wire  signed [5:0] sext_ln840_43_fu_3312_p1;
wire  signed [4:0] sext_ln628_27_fu_1966_p1;
wire  signed [4:0] sext_ln628_30_fu_2047_p1;
wire   [4:0] add_ln840_56_fu_3332_p2;
wire  signed [4:0] sext_ln628_29_fu_2020_p1;
wire  signed [4:0] sext_ln840_fu_2938_p1;
wire   [4:0] add_ln840_57_fu_3342_p2;
wire  signed [5:0] sext_ln840_47_fu_3348_p1;
wire  signed [5:0] sext_ln840_46_fu_3338_p1;
wire  signed [6:0] sext_ln840_6_fu_3367_p1;
wire  signed [6:0] sext_ln840_3_fu_3364_p1;
wire  signed [6:0] sext_ln840_12_fu_3379_p1;
wire  signed [6:0] sext_ln840_9_fu_3376_p1;
wire   [6:0] add_ln840_13_fu_3382_p2;
wire   [6:0] add_ln840_6_fu_3370_p2;
wire  signed [6:0] sext_ln840_18_fu_3397_p1;
wire  signed [6:0] sext_ln840_15_fu_3394_p1;
wire  signed [6:0] sext_ln840_24_fu_3409_p1;
wire  signed [6:0] sext_ln840_21_fu_3406_p1;
wire   [6:0] add_ln840_28_fu_3412_p2;
wire   [6:0] add_ln840_21_fu_3400_p2;
wire  signed [6:0] sext_ln840_30_fu_3427_p1;
wire  signed [6:0] sext_ln840_27_fu_3424_p1;
wire  signed [6:0] sext_ln840_36_fu_3439_p1;
wire  signed [6:0] sext_ln840_33_fu_3436_p1;
wire  signed [6:0] sext_ln840_42_fu_3451_p1;
wire  signed [6:0] sext_ln840_39_fu_3448_p1;
wire  signed [6:0] sext_ln840_48_fu_3463_p1;
wire  signed [6:0] sext_ln840_45_fu_3460_p1;
wire   [6:0] add_ln840_59_fu_3466_p2;
wire   [6:0] add_ln840_52_fu_3454_p2;
wire   [6:0] add_ln840_45_fu_3482_p2;
wire   [6:0] add_ln840_61_fu_3486_p2;
wire   [6:0] add_ln840_30_fu_3478_p2;
wire   [6:0] zext_ln1039_fu_3497_p1;
wire   [0:0] icmp_ln1039_fu_3500_p2;
wire   [0:0] result_V_fu_3505_p2;
wire   [6:0] zext_ln1039_1_fu_3515_p1;
wire   [0:0] icmp_ln1039_1_fu_3518_p2;
wire   [0:0] xor_ln1039_fu_3523_p2;
wire   [6:0] zext_ln1039_2_fu_3533_p1;
wire   [0:0] icmp_ln1039_2_fu_3536_p2;
wire   [0:0] xor_ln1039_1_fu_3541_p2;
wire   [1:0] zext_ln840_2_fu_3511_p1;
wire   [1:0] zext_ln840_1_fu_3547_p1;
wire   [1:0] add_ln840_63_fu_3551_p2;
wire   [1:0] zext_ln840_fu_3529_p1;
wire   [1:0] result_V_2_fu_3557_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
wire    ap_start_int;
wire   [3:0] ret_V_10_fu_1501_p00;
wire   [3:0] ret_V_11_fu_1528_p00;
wire   [3:0] ret_V_12_fu_1555_p00;
wire   [3:0] ret_V_13_fu_1582_p00;
wire   [3:0] ret_V_14_fu_1609_p00;
wire   [3:0] ret_V_15_fu_1636_p00;
wire   [3:0] ret_V_16_fu_1663_p00;
wire   [3:0] ret_V_17_fu_1690_p00;
wire   [3:0] ret_V_18_fu_1717_p00;
wire   [3:0] ret_V_19_fu_1744_p00;
wire   [3:0] ret_V_1_fu_1258_p00;
wire   [3:0] ret_V_20_fu_1771_p00;
wire   [3:0] ret_V_21_fu_1798_p00;
wire   [3:0] ret_V_22_fu_1825_p00;
wire   [3:0] ret_V_23_fu_1852_p00;
wire   [3:0] ret_V_24_fu_1879_p00;
wire   [3:0] ret_V_25_fu_1906_p00;
wire   [3:0] ret_V_26_fu_1933_p00;
wire   [3:0] ret_V_27_fu_1960_p00;
wire   [3:0] ret_V_28_fu_1987_p00;
wire   [3:0] ret_V_29_fu_2014_p00;
wire   [3:0] ret_V_2_fu_1285_p00;
wire   [3:0] ret_V_30_fu_2041_p00;
wire   [3:0] ret_V_31_fu_2068_p00;
wire   [3:0] ret_V_32_fu_2095_p00;
wire   [3:0] ret_V_33_fu_2122_p00;
wire   [3:0] ret_V_34_fu_2149_p00;
wire   [3:0] ret_V_35_fu_2176_p00;
wire   [3:0] ret_V_36_fu_2203_p00;
wire   [3:0] ret_V_37_fu_2230_p00;
wire   [3:0] ret_V_38_fu_2257_p00;
wire   [3:0] ret_V_39_fu_2284_p00;
wire   [3:0] ret_V_3_fu_1312_p00;
wire   [3:0] ret_V_40_fu_2311_p00;
wire   [3:0] ret_V_41_fu_2338_p00;
wire   [3:0] ret_V_42_fu_2365_p00;
wire   [3:0] ret_V_43_fu_2392_p00;
wire   [3:0] ret_V_44_fu_2419_p00;
wire   [3:0] ret_V_45_fu_2446_p00;
wire   [3:0] ret_V_46_fu_2473_p00;
wire   [3:0] ret_V_47_fu_2500_p00;
wire   [3:0] ret_V_48_fu_2527_p00;
wire   [3:0] ret_V_49_fu_2554_p00;
wire   [3:0] ret_V_4_fu_1339_p00;
wire   [3:0] ret_V_50_fu_2581_p00;
wire   [3:0] ret_V_51_fu_2608_p00;
wire   [3:0] ret_V_52_fu_2635_p00;
wire   [3:0] ret_V_53_fu_2662_p00;
wire   [3:0] ret_V_54_fu_2689_p00;
wire   [3:0] ret_V_55_fu_2716_p00;
wire   [3:0] ret_V_56_fu_2743_p00;
wire   [3:0] ret_V_57_fu_2770_p00;
wire   [3:0] ret_V_58_fu_2797_p00;
wire   [3:0] ret_V_59_fu_2824_p00;
wire   [3:0] ret_V_5_fu_1366_p00;
wire   [3:0] ret_V_60_fu_2851_p00;
wire   [3:0] ret_V_61_fu_2878_p00;
wire   [3:0] ret_V_62_fu_2905_p00;
wire   [3:0] ret_V_63_fu_2932_p00;
wire   [3:0] ret_V_6_fu_1393_p00;
wire   [3:0] ret_V_7_fu_1420_p00;
wire   [3:0] ret_V_8_fu_1447_p00;
wire   [3:0] ret_V_9_fu_1474_p00;
wire   [3:0] ret_V_fu_1231_p00;
reg    ap_condition_2615;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_2_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MVAU_hls_2_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MVAU_hls_2_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U1(
    .din0(ret_V_fu_1231_p0),
    .din1(local_temp_V_reg_3600),
    .dout(ret_V_fu_1231_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(ret_V_1_fu_1258_p0),
    .din1(local_temp_V_1_reg_3605),
    .dout(ret_V_1_fu_1258_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(ret_V_2_fu_1285_p0),
    .din1(local_temp_V_2_reg_3610),
    .dout(ret_V_2_fu_1285_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(ret_V_3_fu_1312_p0),
    .din1(local_temp_V_3_reg_3615),
    .dout(ret_V_3_fu_1312_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U5(
    .din0(ret_V_4_fu_1339_p0),
    .din1(local_temp_V_4_reg_3620),
    .dout(ret_V_4_fu_1339_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U6(
    .din0(ret_V_5_fu_1366_p0),
    .din1(local_temp_V_5_reg_3625),
    .dout(ret_V_5_fu_1366_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U7(
    .din0(ret_V_6_fu_1393_p0),
    .din1(local_temp_V_6_reg_3630),
    .dout(ret_V_6_fu_1393_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U8(
    .din0(ret_V_7_fu_1420_p0),
    .din1(local_temp_V_7_reg_3635),
    .dout(ret_V_7_fu_1420_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U9(
    .din0(ret_V_8_fu_1447_p0),
    .din1(local_temp_V_8_reg_3640),
    .dout(ret_V_8_fu_1447_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U10(
    .din0(ret_V_9_fu_1474_p0),
    .din1(local_temp_V_9_reg_3645),
    .dout(ret_V_9_fu_1474_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U11(
    .din0(ret_V_10_fu_1501_p0),
    .din1(local_temp_V_10_reg_3650),
    .dout(ret_V_10_fu_1501_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U12(
    .din0(ret_V_11_fu_1528_p0),
    .din1(local_temp_V_11_reg_3655),
    .dout(ret_V_11_fu_1528_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U13(
    .din0(ret_V_12_fu_1555_p0),
    .din1(local_temp_V_12_reg_3660),
    .dout(ret_V_12_fu_1555_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U14(
    .din0(ret_V_13_fu_1582_p0),
    .din1(local_temp_V_13_reg_3665),
    .dout(ret_V_13_fu_1582_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U15(
    .din0(ret_V_14_fu_1609_p0),
    .din1(local_temp_V_14_reg_3670),
    .dout(ret_V_14_fu_1609_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U16(
    .din0(ret_V_15_fu_1636_p0),
    .din1(local_temp_V_15_reg_3675),
    .dout(ret_V_15_fu_1636_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U17(
    .din0(ret_V_16_fu_1663_p0),
    .din1(local_temp_V_16_reg_3680),
    .dout(ret_V_16_fu_1663_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U18(
    .din0(ret_V_17_fu_1690_p0),
    .din1(local_temp_V_17_reg_3685),
    .dout(ret_V_17_fu_1690_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U19(
    .din0(ret_V_18_fu_1717_p0),
    .din1(local_temp_V_18_reg_3690),
    .dout(ret_V_18_fu_1717_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U20(
    .din0(ret_V_19_fu_1744_p0),
    .din1(local_temp_V_19_reg_3695),
    .dout(ret_V_19_fu_1744_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U21(
    .din0(ret_V_20_fu_1771_p0),
    .din1(local_temp_V_20_reg_3700),
    .dout(ret_V_20_fu_1771_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U22(
    .din0(ret_V_21_fu_1798_p0),
    .din1(local_temp_V_21_reg_3705),
    .dout(ret_V_21_fu_1798_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U23(
    .din0(ret_V_22_fu_1825_p0),
    .din1(local_temp_V_22_reg_3710),
    .dout(ret_V_22_fu_1825_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U24(
    .din0(ret_V_23_fu_1852_p0),
    .din1(local_temp_V_23_reg_3715),
    .dout(ret_V_23_fu_1852_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U25(
    .din0(ret_V_24_fu_1879_p0),
    .din1(local_temp_V_24_reg_3720),
    .dout(ret_V_24_fu_1879_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U26(
    .din0(ret_V_25_fu_1906_p0),
    .din1(local_temp_V_25_reg_3725),
    .dout(ret_V_25_fu_1906_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U27(
    .din0(ret_V_26_fu_1933_p0),
    .din1(local_temp_V_26_reg_3730),
    .dout(ret_V_26_fu_1933_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U28(
    .din0(ret_V_27_fu_1960_p0),
    .din1(local_temp_V_27_reg_3735),
    .dout(ret_V_27_fu_1960_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U29(
    .din0(ret_V_28_fu_1987_p0),
    .din1(local_temp_V_28_reg_3740),
    .dout(ret_V_28_fu_1987_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U30(
    .din0(ret_V_29_fu_2014_p0),
    .din1(local_temp_V_29_reg_3745),
    .dout(ret_V_29_fu_2014_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U31(
    .din0(ret_V_30_fu_2041_p0),
    .din1(local_temp_V_30_reg_3750),
    .dout(ret_V_30_fu_2041_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U32(
    .din0(ret_V_31_fu_2068_p0),
    .din1(local_temp_V_31_reg_3755),
    .dout(ret_V_31_fu_2068_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U33(
    .din0(ret_V_32_fu_2095_p0),
    .din1(local_temp_V_32_reg_3760),
    .dout(ret_V_32_fu_2095_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U34(
    .din0(ret_V_33_fu_2122_p0),
    .din1(local_temp_V_33_reg_3765),
    .dout(ret_V_33_fu_2122_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U35(
    .din0(ret_V_34_fu_2149_p0),
    .din1(local_temp_V_34_reg_3770),
    .dout(ret_V_34_fu_2149_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U36(
    .din0(ret_V_35_fu_2176_p0),
    .din1(local_temp_V_35_reg_3775),
    .dout(ret_V_35_fu_2176_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U37(
    .din0(ret_V_36_fu_2203_p0),
    .din1(local_temp_V_36_reg_3780),
    .dout(ret_V_36_fu_2203_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U38(
    .din0(ret_V_37_fu_2230_p0),
    .din1(local_temp_V_37_reg_3785),
    .dout(ret_V_37_fu_2230_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U39(
    .din0(ret_V_38_fu_2257_p0),
    .din1(local_temp_V_38_reg_3790),
    .dout(ret_V_38_fu_2257_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U40(
    .din0(ret_V_39_fu_2284_p0),
    .din1(local_temp_V_39_reg_3795),
    .dout(ret_V_39_fu_2284_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U41(
    .din0(ret_V_40_fu_2311_p0),
    .din1(local_temp_V_40_reg_3800),
    .dout(ret_V_40_fu_2311_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U42(
    .din0(ret_V_41_fu_2338_p0),
    .din1(local_temp_V_41_reg_3805),
    .dout(ret_V_41_fu_2338_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U43(
    .din0(ret_V_42_fu_2365_p0),
    .din1(local_temp_V_42_reg_3810),
    .dout(ret_V_42_fu_2365_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U44(
    .din0(ret_V_43_fu_2392_p0),
    .din1(local_temp_V_43_reg_3815),
    .dout(ret_V_43_fu_2392_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U45(
    .din0(ret_V_44_fu_2419_p0),
    .din1(local_temp_V_44_reg_3820),
    .dout(ret_V_44_fu_2419_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U46(
    .din0(ret_V_45_fu_2446_p0),
    .din1(local_temp_V_45_reg_3825),
    .dout(ret_V_45_fu_2446_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U47(
    .din0(ret_V_46_fu_2473_p0),
    .din1(local_temp_V_46_reg_3830),
    .dout(ret_V_46_fu_2473_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U48(
    .din0(ret_V_47_fu_2500_p0),
    .din1(local_temp_V_47_reg_3835),
    .dout(ret_V_47_fu_2500_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U49(
    .din0(ret_V_48_fu_2527_p0),
    .din1(local_temp_V_48_reg_3840),
    .dout(ret_V_48_fu_2527_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U50(
    .din0(ret_V_49_fu_2554_p0),
    .din1(local_temp_V_49_reg_3845),
    .dout(ret_V_49_fu_2554_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U51(
    .din0(ret_V_50_fu_2581_p0),
    .din1(local_temp_V_50_reg_3850),
    .dout(ret_V_50_fu_2581_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U52(
    .din0(ret_V_51_fu_2608_p0),
    .din1(local_temp_V_51_reg_3855),
    .dout(ret_V_51_fu_2608_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U53(
    .din0(ret_V_52_fu_2635_p0),
    .din1(local_temp_V_52_reg_3860),
    .dout(ret_V_52_fu_2635_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U54(
    .din0(ret_V_53_fu_2662_p0),
    .din1(local_temp_V_53_reg_3865),
    .dout(ret_V_53_fu_2662_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U55(
    .din0(ret_V_54_fu_2689_p0),
    .din1(local_temp_V_54_reg_3870),
    .dout(ret_V_54_fu_2689_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U56(
    .din0(ret_V_55_fu_2716_p0),
    .din1(local_temp_V_55_reg_3875),
    .dout(ret_V_55_fu_2716_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U57(
    .din0(ret_V_56_fu_2743_p0),
    .din1(local_temp_V_56_reg_3880),
    .dout(ret_V_56_fu_2743_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U58(
    .din0(ret_V_57_fu_2770_p0),
    .din1(local_temp_V_57_reg_3885),
    .dout(ret_V_57_fu_2770_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U59(
    .din0(ret_V_58_fu_2797_p0),
    .din1(local_temp_V_58_reg_3890),
    .dout(ret_V_58_fu_2797_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U60(
    .din0(ret_V_59_fu_2824_p0),
    .din1(local_temp_V_59_reg_3895),
    .dout(ret_V_59_fu_2824_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U61(
    .din0(ret_V_60_fu_2851_p0),
    .din1(local_temp_V_60_reg_3900),
    .dout(ret_V_60_fu_2851_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U62(
    .din0(ret_V_61_fu_2878_p0),
    .din1(local_temp_V_61_reg_3905),
    .dout(ret_V_61_fu_2878_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U63(
    .din0(ret_V_62_fu_2905_p0),
    .din1(local_temp_V_62_reg_3910),
    .dout(ret_V_62_fu_2905_p2)
);

MVAU_hls_2_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U64(
    .din0(ret_V_63_fu_2932_p0),
    .din1(local_temp_V_63_reg_3915),
    .dout(ret_V_63_fu_2932_p2)
);

MVAU_hls_2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2615)) begin
        if ((icmp_ln249_fu_530_p2 == 1'd0)) begin
            i_fu_448 <= i_2_fu_536_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_448 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2615)) begin
        if ((icmp_ln249_fu_530_p2 == 1'd0)) begin
            nf_1_fu_444 <= nf_4_fu_1199_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_444 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_3593_pp0_iter0_reg == 1'd0))) begin
        add_ln840_12_reg_3935 <= add_ln840_12_fu_3040_p2;
        add_ln840_17_reg_3940 <= add_ln840_17_fu_3066_p2;
        add_ln840_20_reg_3945 <= add_ln840_20_fu_3092_p2;
        add_ln840_24_reg_3950 <= add_ln840_24_fu_3118_p2;
        add_ln840_27_reg_3955 <= add_ln840_27_fu_3144_p2;
        add_ln840_2_reg_3920 <= add_ln840_2_fu_2962_p2;
        add_ln840_33_reg_3960 <= add_ln840_33_fu_3170_p2;
        add_ln840_36_reg_3965 <= add_ln840_36_fu_3196_p2;
        add_ln840_40_reg_3970 <= add_ln840_40_fu_3222_p2;
        add_ln840_43_reg_3975 <= add_ln840_43_fu_3248_p2;
        add_ln840_48_reg_3980 <= add_ln840_48_fu_3274_p2;
        add_ln840_51_reg_3985 <= add_ln840_51_fu_3300_p2;
        add_ln840_55_reg_3990 <= add_ln840_55_fu_3326_p2;
        add_ln840_58_reg_3995 <= add_ln840_58_fu_3352_p2;
        add_ln840_5_reg_3925 <= add_ln840_5_fu_2988_p2;
        add_ln840_9_reg_3930 <= add_ln840_9_fu_3014_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln249_reg_3593_pp0_iter1_reg == 1'd0))) begin
        add_ln840_14_reg_4015 <= add_ln840_14_fu_3388_p2;
        add_ln840_29_reg_4020 <= add_ln840_29_fu_3418_p2;
        add_ln840_37_reg_4025 <= add_ln840_37_fu_3430_p2;
        add_ln840_44_reg_4030 <= add_ln840_44_fu_3442_p2;
        add_ln840_60_reg_4035 <= add_ln840_60_fu_3472_p2;
        p_ZL7threshs_0_load_reg_4040 <= p_ZL7threshs_0_q0;
        p_ZL7threshs_1_load_reg_4045 <= p_ZL7threshs_1_q0;
        p_ZL7threshs_2_load_reg_4050 <= p_ZL7threshs_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4) & (icmp_ln249_reg_3593_pp0_iter2_reg == 1'd0))) begin
        add_ln840_62_reg_4055 <= add_ln840_62_fu_3491_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_3593 <= icmp_ln249_fu_530_p2;
        nf_3_reg_3588 <= ap_sig_allocacmp_nf_3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_3593_pp0_iter1_reg <= icmp_ln249_reg_3593;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_3593_pp0_iter2_reg <= icmp_ln249_reg_3593_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln249_reg_3593_pp0_iter3_reg <= icmp_ln249_reg_3593_pp0_iter2_reg;
        p_ZL7threshs_0_load_reg_4040_pp0_iter3_reg <= p_ZL7threshs_0_load_reg_4040;
        p_ZL7threshs_1_load_reg_4045_pp0_iter3_reg <= p_ZL7threshs_1_load_reg_4045;
        p_ZL7threshs_2_load_reg_4050_pp0_iter3_reg <= p_ZL7threshs_2_load_reg_4050;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0))) begin
        local_temp_V_10_reg_3650 <= {{in1_V_TDATA[21:20]}};
        local_temp_V_11_reg_3655 <= {{in1_V_TDATA[23:22]}};
        local_temp_V_12_reg_3660 <= {{in1_V_TDATA[25:24]}};
        local_temp_V_13_reg_3665 <= {{in1_V_TDATA[27:26]}};
        local_temp_V_14_reg_3670 <= {{in1_V_TDATA[29:28]}};
        local_temp_V_15_reg_3675 <= {{in1_V_TDATA[31:30]}};
        local_temp_V_16_reg_3680 <= {{in1_V_TDATA[33:32]}};
        local_temp_V_17_reg_3685 <= {{in1_V_TDATA[35:34]}};
        local_temp_V_18_reg_3690 <= {{in1_V_TDATA[37:36]}};
        local_temp_V_19_reg_3695 <= {{in1_V_TDATA[39:38]}};
        local_temp_V_1_reg_3605 <= {{in1_V_TDATA[3:2]}};
        local_temp_V_20_reg_3700 <= {{in1_V_TDATA[41:40]}};
        local_temp_V_21_reg_3705 <= {{in1_V_TDATA[43:42]}};
        local_temp_V_22_reg_3710 <= {{in1_V_TDATA[45:44]}};
        local_temp_V_23_reg_3715 <= {{in1_V_TDATA[47:46]}};
        local_temp_V_24_reg_3720 <= {{in1_V_TDATA[49:48]}};
        local_temp_V_25_reg_3725 <= {{in1_V_TDATA[51:50]}};
        local_temp_V_26_reg_3730 <= {{in1_V_TDATA[53:52]}};
        local_temp_V_27_reg_3735 <= {{in1_V_TDATA[55:54]}};
        local_temp_V_28_reg_3740 <= {{in1_V_TDATA[57:56]}};
        local_temp_V_29_reg_3745 <= {{in1_V_TDATA[59:58]}};
        local_temp_V_2_reg_3610 <= {{in1_V_TDATA[5:4]}};
        local_temp_V_30_reg_3750 <= {{in1_V_TDATA[61:60]}};
        local_temp_V_31_reg_3755 <= {{in1_V_TDATA[63:62]}};
        local_temp_V_32_reg_3760 <= {{in1_V_TDATA[65:64]}};
        local_temp_V_33_reg_3765 <= {{in1_V_TDATA[67:66]}};
        local_temp_V_34_reg_3770 <= {{in1_V_TDATA[69:68]}};
        local_temp_V_35_reg_3775 <= {{in1_V_TDATA[71:70]}};
        local_temp_V_36_reg_3780 <= {{in1_V_TDATA[73:72]}};
        local_temp_V_37_reg_3785 <= {{in1_V_TDATA[75:74]}};
        local_temp_V_38_reg_3790 <= {{in1_V_TDATA[77:76]}};
        local_temp_V_39_reg_3795 <= {{in1_V_TDATA[79:78]}};
        local_temp_V_3_reg_3615 <= {{in1_V_TDATA[7:6]}};
        local_temp_V_40_reg_3800 <= {{in1_V_TDATA[81:80]}};
        local_temp_V_41_reg_3805 <= {{in1_V_TDATA[83:82]}};
        local_temp_V_42_reg_3810 <= {{in1_V_TDATA[85:84]}};
        local_temp_V_43_reg_3815 <= {{in1_V_TDATA[87:86]}};
        local_temp_V_44_reg_3820 <= {{in1_V_TDATA[89:88]}};
        local_temp_V_45_reg_3825 <= {{in1_V_TDATA[91:90]}};
        local_temp_V_46_reg_3830 <= {{in1_V_TDATA[93:92]}};
        local_temp_V_47_reg_3835 <= {{in1_V_TDATA[95:94]}};
        local_temp_V_48_reg_3840 <= {{in1_V_TDATA[97:96]}};
        local_temp_V_49_reg_3845 <= {{in1_V_TDATA[99:98]}};
        local_temp_V_4_reg_3620 <= {{in1_V_TDATA[9:8]}};
        local_temp_V_50_reg_3850 <= {{in1_V_TDATA[101:100]}};
        local_temp_V_51_reg_3855 <= {{in1_V_TDATA[103:102]}};
        local_temp_V_52_reg_3860 <= {{in1_V_TDATA[105:104]}};
        local_temp_V_53_reg_3865 <= {{in1_V_TDATA[107:106]}};
        local_temp_V_54_reg_3870 <= {{in1_V_TDATA[109:108]}};
        local_temp_V_55_reg_3875 <= {{in1_V_TDATA[111:110]}};
        local_temp_V_56_reg_3880 <= {{in1_V_TDATA[113:112]}};
        local_temp_V_57_reg_3885 <= {{in1_V_TDATA[115:114]}};
        local_temp_V_58_reg_3890 <= {{in1_V_TDATA[117:116]}};
        local_temp_V_59_reg_3895 <= {{in1_V_TDATA[119:118]}};
        local_temp_V_5_reg_3625 <= {{in1_V_TDATA[11:10]}};
        local_temp_V_60_reg_3900 <= {{in1_V_TDATA[121:120]}};
        local_temp_V_61_reg_3905 <= {{in1_V_TDATA[123:122]}};
        local_temp_V_62_reg_3910 <= {{in1_V_TDATA[125:124]}};
        local_temp_V_63_reg_3915 <= {{in1_V_TDATA[127:126]}};
        local_temp_V_6_reg_3630 <= {{in1_V_TDATA[13:12]}};
        local_temp_V_7_reg_3635 <= {{in1_V_TDATA[15:14]}};
        local_temp_V_8_reg_3640 <= {{in1_V_TDATA[17:16]}};
        local_temp_V_9_reg_3645 <= {{in1_V_TDATA[19:18]}};
        local_temp_V_reg_3600 <= local_temp_V_fu_553_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (icmp_ln253_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0))) begin
        p_Val2_s_fu_452 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_448;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_3 = nf_1_fu_444;
    end
end

always @ (*) begin
    if (((ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        in1_V_TDATA_blk_n = in1_V_TVALID;
    end else begin
        in1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0))) begin
        in1_V_TREADY = 1'b1;
    end else begin
        in1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out0_V_TVALID = 1'b1;
    end else begin
        out0_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else if (((~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))) & (icmp_ln249_reg_3593_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_3020_p2 = ($signed(sext_ln628_52_fu_2641_p1) + $signed(sext_ln628_51_fu_2614_p1));

assign add_ln840_11_fu_3030_p2 = ($signed(sext_ln628_54_fu_2695_p1) + $signed(sext_ln628_53_fu_2668_p1));

assign add_ln840_12_fu_3040_p2 = ($signed(sext_ln840_11_fu_3036_p1) + $signed(sext_ln840_10_fu_3026_p1));

assign add_ln840_13_fu_3382_p2 = ($signed(sext_ln840_12_fu_3379_p1) + $signed(sext_ln840_9_fu_3376_p1));

assign add_ln840_14_fu_3388_p2 = (add_ln840_13_fu_3382_p2 + add_ln840_6_fu_3370_p2);

assign add_ln840_15_fu_3046_p2 = ($signed(sext_ln628_32_fu_2101_p1) + $signed(sext_ln628_31_fu_2074_p1));

assign add_ln840_16_fu_3056_p2 = ($signed(sext_ln628_34_fu_2155_p1) + $signed(sext_ln628_33_fu_2128_p1));

assign add_ln840_17_fu_3066_p2 = ($signed(sext_ln840_14_fu_3062_p1) + $signed(sext_ln840_13_fu_3052_p1));

assign add_ln840_18_fu_3072_p2 = ($signed(sext_ln628_36_fu_2209_p1) + $signed(sext_ln628_35_fu_2182_p1));

assign add_ln840_19_fu_3082_p2 = ($signed(sext_ln628_38_fu_2263_p1) + $signed(sext_ln628_37_fu_2236_p1));

assign add_ln840_1_fu_2952_p2 = ($signed(sext_ln628_60_fu_2857_p1) + $signed(sext_ln628_59_fu_2830_p1));

assign add_ln840_20_fu_3092_p2 = ($signed(sext_ln840_17_fu_3088_p1) + $signed(sext_ln840_16_fu_3078_p1));

assign add_ln840_21_fu_3400_p2 = ($signed(sext_ln840_18_fu_3397_p1) + $signed(sext_ln840_15_fu_3394_p1));

assign add_ln840_22_fu_3098_p2 = ($signed(sext_ln628_40_fu_2317_p1) + $signed(sext_ln628_39_fu_2290_p1));

assign add_ln840_23_fu_3108_p2 = ($signed(sext_ln628_42_fu_2371_p1) + $signed(sext_ln628_41_fu_2344_p1));

assign add_ln840_24_fu_3118_p2 = ($signed(sext_ln840_20_fu_3114_p1) + $signed(sext_ln840_19_fu_3104_p1));

assign add_ln840_25_fu_3124_p2 = ($signed(sext_ln628_44_fu_2425_p1) + $signed(sext_ln628_43_fu_2398_p1));

assign add_ln840_26_fu_3134_p2 = ($signed(sext_ln628_46_fu_2479_p1) + $signed(sext_ln628_45_fu_2452_p1));

assign add_ln840_27_fu_3144_p2 = ($signed(sext_ln840_23_fu_3140_p1) + $signed(sext_ln840_22_fu_3130_p1));

assign add_ln840_28_fu_3412_p2 = ($signed(sext_ln840_24_fu_3409_p1) + $signed(sext_ln840_21_fu_3406_p1));

assign add_ln840_29_fu_3418_p2 = (add_ln840_28_fu_3412_p2 + add_ln840_21_fu_3400_p2);

assign add_ln840_2_fu_2962_p2 = ($signed(sext_ln840_2_fu_2958_p1) + $signed(sext_ln840_1_fu_2948_p1));

assign add_ln840_30_fu_3478_p2 = (add_ln840_29_reg_4020 + add_ln840_14_reg_4015);

assign add_ln840_31_fu_3150_p2 = ($signed(sext_ln628_1_fu_1264_p1) + $signed(sext_ln628_2_fu_1291_p1));

assign add_ln840_32_fu_3160_p2 = ($signed(sext_ln628_fu_1237_p1) + $signed(sext_ln628_4_fu_1345_p1));

assign add_ln840_33_fu_3170_p2 = ($signed(sext_ln840_26_fu_3166_p1) + $signed(sext_ln840_25_fu_3156_p1));

assign add_ln840_34_fu_3176_p2 = ($signed(sext_ln628_3_fu_1318_p1) + $signed(sext_ln628_6_fu_1399_p1));

assign add_ln840_35_fu_3186_p2 = ($signed(sext_ln628_5_fu_1372_p1) + $signed(sext_ln628_8_fu_1453_p1));

assign add_ln840_36_fu_3196_p2 = ($signed(sext_ln840_29_fu_3192_p1) + $signed(sext_ln840_28_fu_3182_p1));

assign add_ln840_37_fu_3430_p2 = ($signed(sext_ln840_30_fu_3427_p1) + $signed(sext_ln840_27_fu_3424_p1));

assign add_ln840_38_fu_3202_p2 = ($signed(sext_ln628_7_fu_1426_p1) + $signed(sext_ln628_10_fu_1507_p1));

assign add_ln840_39_fu_3212_p2 = ($signed(sext_ln628_9_fu_1480_p1) + $signed(sext_ln628_12_fu_1561_p1));

assign add_ln840_3_fu_2968_p2 = ($signed(sext_ln628_56_fu_2749_p1) + $signed(sext_ln628_55_fu_2722_p1));

assign add_ln840_40_fu_3222_p2 = ($signed(sext_ln840_32_fu_3218_p1) + $signed(sext_ln840_31_fu_3208_p1));

assign add_ln840_41_fu_3228_p2 = ($signed(sext_ln628_11_fu_1534_p1) + $signed(sext_ln628_14_fu_1615_p1));

assign add_ln840_42_fu_3238_p2 = ($signed(sext_ln628_13_fu_1588_p1) + $signed(sext_ln628_16_fu_1669_p1));

assign add_ln840_43_fu_3248_p2 = ($signed(sext_ln840_35_fu_3244_p1) + $signed(sext_ln840_34_fu_3234_p1));

assign add_ln840_44_fu_3442_p2 = ($signed(sext_ln840_36_fu_3439_p1) + $signed(sext_ln840_33_fu_3436_p1));

assign add_ln840_45_fu_3482_p2 = (add_ln840_44_reg_4030 + add_ln840_37_reg_4025);

assign add_ln840_46_fu_3254_p2 = ($signed(sext_ln628_15_fu_1642_p1) + $signed(sext_ln628_18_fu_1723_p1));

assign add_ln840_47_fu_3264_p2 = ($signed(sext_ln628_17_fu_1696_p1) + $signed(sext_ln628_20_fu_1777_p1));

assign add_ln840_48_fu_3274_p2 = ($signed(sext_ln840_38_fu_3270_p1) + $signed(sext_ln840_37_fu_3260_p1));

assign add_ln840_49_fu_3280_p2 = ($signed(sext_ln628_19_fu_1750_p1) + $signed(sext_ln628_22_fu_1831_p1));

assign add_ln840_4_fu_2978_p2 = ($signed(sext_ln628_58_fu_2803_p1) + $signed(sext_ln628_57_fu_2776_p1));

assign add_ln840_50_fu_3290_p2 = ($signed(sext_ln628_21_fu_1804_p1) + $signed(sext_ln628_24_fu_1885_p1));

assign add_ln840_51_fu_3300_p2 = ($signed(sext_ln840_41_fu_3296_p1) + $signed(sext_ln840_40_fu_3286_p1));

assign add_ln840_52_fu_3454_p2 = ($signed(sext_ln840_42_fu_3451_p1) + $signed(sext_ln840_39_fu_3448_p1));

assign add_ln840_53_fu_3306_p2 = ($signed(sext_ln628_23_fu_1858_p1) + $signed(sext_ln628_26_fu_1939_p1));

assign add_ln840_54_fu_3316_p2 = ($signed(sext_ln628_25_fu_1912_p1) + $signed(sext_ln628_28_fu_1993_p1));

assign add_ln840_55_fu_3326_p2 = ($signed(sext_ln840_44_fu_3322_p1) + $signed(sext_ln840_43_fu_3312_p1));

assign add_ln840_56_fu_3332_p2 = ($signed(sext_ln628_27_fu_1966_p1) + $signed(sext_ln628_30_fu_2047_p1));

assign add_ln840_57_fu_3342_p2 = ($signed(sext_ln628_29_fu_2020_p1) + $signed(sext_ln840_fu_2938_p1));

assign add_ln840_58_fu_3352_p2 = ($signed(sext_ln840_47_fu_3348_p1) + $signed(sext_ln840_46_fu_3338_p1));

assign add_ln840_59_fu_3466_p2 = ($signed(sext_ln840_48_fu_3463_p1) + $signed(sext_ln840_45_fu_3460_p1));

assign add_ln840_5_fu_2988_p2 = ($signed(sext_ln840_5_fu_2984_p1) + $signed(sext_ln840_4_fu_2974_p1));

assign add_ln840_60_fu_3472_p2 = (add_ln840_59_fu_3466_p2 + add_ln840_52_fu_3454_p2);

assign add_ln840_61_fu_3486_p2 = (add_ln840_60_reg_4035 + add_ln840_45_fu_3482_p2);

assign add_ln840_62_fu_3491_p2 = (add_ln840_61_fu_3486_p2 + add_ln840_30_fu_3478_p2);

assign add_ln840_63_fu_3551_p2 = (zext_ln840_2_fu_3511_p1 + zext_ln840_1_fu_3547_p1);

assign add_ln840_6_fu_3370_p2 = ($signed(sext_ln840_6_fu_3367_p1) + $signed(sext_ln840_3_fu_3364_p1));

assign add_ln840_7_fu_2994_p2 = ($signed(sext_ln628_48_fu_2533_p1) + $signed(sext_ln628_47_fu_2506_p1));

assign add_ln840_8_fu_3004_p2 = ($signed(sext_ln628_50_fu_2587_p1) + $signed(sext_ln628_49_fu_2560_p1));

assign add_ln840_9_fu_3014_p2 = ($signed(sext_ln840_8_fu_3010_p1) + $signed(sext_ln840_7_fu_3000_p1));

assign add_ln840_fu_2942_p2 = ($signed(sext_ln628_61_fu_2884_p1) + $signed(sext_ln628_62_fu_2911_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_2615 = (~((ap_start_int == 1'b0) | ((in1_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((icmp_ln249_reg_3593_pp0_iter3_reg == 1'd0) & (out0_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op27_read_state1 = ((icmp_ln253_fu_542_p2 == 1'd1) & (icmp_ln249_fu_530_p2 == 1'd0));
end

assign i_2_fu_536_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln1039_1_fu_3518_p2 = (($signed(add_ln840_62_reg_4055) < $signed(zext_ln1039_1_fu_3515_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_3536_p2 = (($signed(add_ln840_62_reg_4055) < $signed(zext_ln1039_2_fu_3533_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_3500_p2 = (($signed(add_ln840_62_reg_4055) < $signed(zext_ln1039_fu_3497_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_530_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_3593_pp0_iter0_reg = icmp_ln249_reg_3593;

assign icmp_ln253_fu_542_p2 = ((ap_sig_allocacmp_nf_3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_1193_p2 = ((nf_fu_1187_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_3358_p1 = nf_3_reg_3588;

assign local_temp_V_fu_553_p1 = in1_V_TDATA[1:0];

assign nf_4_fu_1199_p3 = ((icmp_ln302_fu_1193_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_1187_p2);

assign nf_fu_1187_p2 = (ap_sig_allocacmp_nf_3 + 32'd1);

assign out0_V_TDATA = result_V_2_fu_3557_p2;

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_3358_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_3358_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_3358_p1;

assign r_V_10_fu_1484_p4 = {{p_Val2_s_fu_452[21:20]}};

assign r_V_11_fu_1511_p4 = {{p_Val2_s_fu_452[23:22]}};

assign r_V_12_fu_1538_p4 = {{p_Val2_s_fu_452[25:24]}};

assign r_V_13_fu_1565_p4 = {{p_Val2_s_fu_452[27:26]}};

assign r_V_14_fu_1592_p4 = {{p_Val2_s_fu_452[29:28]}};

assign r_V_15_fu_1619_p4 = {{p_Val2_s_fu_452[31:30]}};

assign r_V_16_fu_1646_p4 = {{p_Val2_s_fu_452[33:32]}};

assign r_V_17_fu_1673_p4 = {{p_Val2_s_fu_452[35:34]}};

assign r_V_18_fu_1700_p4 = {{p_Val2_s_fu_452[37:36]}};

assign r_V_19_fu_1727_p4 = {{p_Val2_s_fu_452[39:38]}};

assign r_V_1_fu_1241_p4 = {{p_Val2_s_fu_452[3:2]}};

assign r_V_20_fu_1754_p4 = {{p_Val2_s_fu_452[41:40]}};

assign r_V_21_fu_1781_p4 = {{p_Val2_s_fu_452[43:42]}};

assign r_V_22_fu_1808_p4 = {{p_Val2_s_fu_452[45:44]}};

assign r_V_23_fu_1835_p4 = {{p_Val2_s_fu_452[47:46]}};

assign r_V_24_fu_1862_p4 = {{p_Val2_s_fu_452[49:48]}};

assign r_V_25_fu_1889_p4 = {{p_Val2_s_fu_452[51:50]}};

assign r_V_26_fu_1916_p4 = {{p_Val2_s_fu_452[53:52]}};

assign r_V_27_fu_1943_p4 = {{p_Val2_s_fu_452[55:54]}};

assign r_V_28_fu_1970_p4 = {{p_Val2_s_fu_452[57:56]}};

assign r_V_29_fu_1997_p4 = {{p_Val2_s_fu_452[59:58]}};

assign r_V_2_fu_1268_p4 = {{p_Val2_s_fu_452[5:4]}};

assign r_V_30_fu_2024_p4 = {{p_Val2_s_fu_452[61:60]}};

assign r_V_31_fu_2051_p4 = {{p_Val2_s_fu_452[63:62]}};

assign r_V_32_fu_2078_p4 = {{p_Val2_s_fu_452[65:64]}};

assign r_V_33_fu_2105_p4 = {{p_Val2_s_fu_452[67:66]}};

assign r_V_34_fu_2132_p4 = {{p_Val2_s_fu_452[69:68]}};

assign r_V_35_fu_2159_p4 = {{p_Val2_s_fu_452[71:70]}};

assign r_V_36_fu_2186_p4 = {{p_Val2_s_fu_452[73:72]}};

assign r_V_37_fu_2213_p4 = {{p_Val2_s_fu_452[75:74]}};

assign r_V_38_fu_2240_p4 = {{p_Val2_s_fu_452[77:76]}};

assign r_V_39_fu_2267_p4 = {{p_Val2_s_fu_452[79:78]}};

assign r_V_3_fu_1295_p4 = {{p_Val2_s_fu_452[7:6]}};

assign r_V_40_fu_2294_p4 = {{p_Val2_s_fu_452[81:80]}};

assign r_V_41_fu_2321_p4 = {{p_Val2_s_fu_452[83:82]}};

assign r_V_42_fu_2348_p4 = {{p_Val2_s_fu_452[85:84]}};

assign r_V_43_fu_2375_p4 = {{p_Val2_s_fu_452[87:86]}};

assign r_V_44_fu_2402_p4 = {{p_Val2_s_fu_452[89:88]}};

assign r_V_45_fu_2429_p4 = {{p_Val2_s_fu_452[91:90]}};

assign r_V_46_fu_2456_p4 = {{p_Val2_s_fu_452[93:92]}};

assign r_V_47_fu_2483_p4 = {{p_Val2_s_fu_452[95:94]}};

assign r_V_48_fu_2510_p4 = {{p_Val2_s_fu_452[97:96]}};

assign r_V_49_fu_2537_p4 = {{p_Val2_s_fu_452[99:98]}};

assign r_V_4_fu_1322_p4 = {{p_Val2_s_fu_452[9:8]}};

assign r_V_50_fu_2564_p4 = {{p_Val2_s_fu_452[101:100]}};

assign r_V_51_fu_2591_p4 = {{p_Val2_s_fu_452[103:102]}};

assign r_V_52_fu_2618_p4 = {{p_Val2_s_fu_452[105:104]}};

assign r_V_53_fu_2645_p4 = {{p_Val2_s_fu_452[107:106]}};

assign r_V_54_fu_2672_p4 = {{p_Val2_s_fu_452[109:108]}};

assign r_V_55_fu_2699_p4 = {{p_Val2_s_fu_452[111:110]}};

assign r_V_56_fu_2726_p4 = {{p_Val2_s_fu_452[113:112]}};

assign r_V_57_fu_2753_p4 = {{p_Val2_s_fu_452[115:114]}};

assign r_V_58_fu_2780_p4 = {{p_Val2_s_fu_452[117:116]}};

assign r_V_59_fu_2807_p4 = {{p_Val2_s_fu_452[119:118]}};

assign r_V_5_fu_1349_p4 = {{p_Val2_s_fu_452[11:10]}};

assign r_V_60_fu_2834_p4 = {{p_Val2_s_fu_452[121:120]}};

assign r_V_61_fu_2861_p4 = {{p_Val2_s_fu_452[123:122]}};

assign r_V_62_fu_2888_p4 = {{p_Val2_s_fu_452[125:124]}};

assign r_V_63_fu_2915_p4 = {{p_Val2_s_fu_452[127:126]}};

assign r_V_6_fu_1376_p4 = {{p_Val2_s_fu_452[13:12]}};

assign r_V_7_fu_1403_p4 = {{p_Val2_s_fu_452[15:14]}};

assign r_V_8_fu_1430_p4 = {{p_Val2_s_fu_452[17:16]}};

assign r_V_9_fu_1457_p4 = {{p_Val2_s_fu_452[19:18]}};

assign r_V_fu_1220_p1 = p_Val2_s_fu_452[1:0];

assign result_V_2_fu_3557_p2 = (add_ln840_63_fu_3551_p2 + zext_ln840_fu_3529_p1);

assign result_V_fu_3505_p2 = (icmp_ln1039_fu_3500_p2 ^ 1'd1);

assign ret_V_10_fu_1501_p0 = ret_V_10_fu_1501_p00;

assign ret_V_10_fu_1501_p00 = r_V_10_fu_1484_p4;

assign ret_V_11_fu_1528_p0 = ret_V_11_fu_1528_p00;

assign ret_V_11_fu_1528_p00 = r_V_11_fu_1511_p4;

assign ret_V_12_fu_1555_p0 = ret_V_12_fu_1555_p00;

assign ret_V_12_fu_1555_p00 = r_V_12_fu_1538_p4;

assign ret_V_13_fu_1582_p0 = ret_V_13_fu_1582_p00;

assign ret_V_13_fu_1582_p00 = r_V_13_fu_1565_p4;

assign ret_V_14_fu_1609_p0 = ret_V_14_fu_1609_p00;

assign ret_V_14_fu_1609_p00 = r_V_14_fu_1592_p4;

assign ret_V_15_fu_1636_p0 = ret_V_15_fu_1636_p00;

assign ret_V_15_fu_1636_p00 = r_V_15_fu_1619_p4;

assign ret_V_16_fu_1663_p0 = ret_V_16_fu_1663_p00;

assign ret_V_16_fu_1663_p00 = r_V_16_fu_1646_p4;

assign ret_V_17_fu_1690_p0 = ret_V_17_fu_1690_p00;

assign ret_V_17_fu_1690_p00 = r_V_17_fu_1673_p4;

assign ret_V_18_fu_1717_p0 = ret_V_18_fu_1717_p00;

assign ret_V_18_fu_1717_p00 = r_V_18_fu_1700_p4;

assign ret_V_19_fu_1744_p0 = ret_V_19_fu_1744_p00;

assign ret_V_19_fu_1744_p00 = r_V_19_fu_1727_p4;

assign ret_V_1_fu_1258_p0 = ret_V_1_fu_1258_p00;

assign ret_V_1_fu_1258_p00 = r_V_1_fu_1241_p4;

assign ret_V_20_fu_1771_p0 = ret_V_20_fu_1771_p00;

assign ret_V_20_fu_1771_p00 = r_V_20_fu_1754_p4;

assign ret_V_21_fu_1798_p0 = ret_V_21_fu_1798_p00;

assign ret_V_21_fu_1798_p00 = r_V_21_fu_1781_p4;

assign ret_V_22_fu_1825_p0 = ret_V_22_fu_1825_p00;

assign ret_V_22_fu_1825_p00 = r_V_22_fu_1808_p4;

assign ret_V_23_fu_1852_p0 = ret_V_23_fu_1852_p00;

assign ret_V_23_fu_1852_p00 = r_V_23_fu_1835_p4;

assign ret_V_24_fu_1879_p0 = ret_V_24_fu_1879_p00;

assign ret_V_24_fu_1879_p00 = r_V_24_fu_1862_p4;

assign ret_V_25_fu_1906_p0 = ret_V_25_fu_1906_p00;

assign ret_V_25_fu_1906_p00 = r_V_25_fu_1889_p4;

assign ret_V_26_fu_1933_p0 = ret_V_26_fu_1933_p00;

assign ret_V_26_fu_1933_p00 = r_V_26_fu_1916_p4;

assign ret_V_27_fu_1960_p0 = ret_V_27_fu_1960_p00;

assign ret_V_27_fu_1960_p00 = r_V_27_fu_1943_p4;

assign ret_V_28_fu_1987_p0 = ret_V_28_fu_1987_p00;

assign ret_V_28_fu_1987_p00 = r_V_28_fu_1970_p4;

assign ret_V_29_fu_2014_p0 = ret_V_29_fu_2014_p00;

assign ret_V_29_fu_2014_p00 = r_V_29_fu_1997_p4;

assign ret_V_2_fu_1285_p0 = ret_V_2_fu_1285_p00;

assign ret_V_2_fu_1285_p00 = r_V_2_fu_1268_p4;

assign ret_V_30_fu_2041_p0 = ret_V_30_fu_2041_p00;

assign ret_V_30_fu_2041_p00 = r_V_30_fu_2024_p4;

assign ret_V_31_fu_2068_p0 = ret_V_31_fu_2068_p00;

assign ret_V_31_fu_2068_p00 = r_V_31_fu_2051_p4;

assign ret_V_32_fu_2095_p0 = ret_V_32_fu_2095_p00;

assign ret_V_32_fu_2095_p00 = r_V_32_fu_2078_p4;

assign ret_V_33_fu_2122_p0 = ret_V_33_fu_2122_p00;

assign ret_V_33_fu_2122_p00 = r_V_33_fu_2105_p4;

assign ret_V_34_fu_2149_p0 = ret_V_34_fu_2149_p00;

assign ret_V_34_fu_2149_p00 = r_V_34_fu_2132_p4;

assign ret_V_35_fu_2176_p0 = ret_V_35_fu_2176_p00;

assign ret_V_35_fu_2176_p00 = r_V_35_fu_2159_p4;

assign ret_V_36_fu_2203_p0 = ret_V_36_fu_2203_p00;

assign ret_V_36_fu_2203_p00 = r_V_36_fu_2186_p4;

assign ret_V_37_fu_2230_p0 = ret_V_37_fu_2230_p00;

assign ret_V_37_fu_2230_p00 = r_V_37_fu_2213_p4;

assign ret_V_38_fu_2257_p0 = ret_V_38_fu_2257_p00;

assign ret_V_38_fu_2257_p00 = r_V_38_fu_2240_p4;

assign ret_V_39_fu_2284_p0 = ret_V_39_fu_2284_p00;

assign ret_V_39_fu_2284_p00 = r_V_39_fu_2267_p4;

assign ret_V_3_fu_1312_p0 = ret_V_3_fu_1312_p00;

assign ret_V_3_fu_1312_p00 = r_V_3_fu_1295_p4;

assign ret_V_40_fu_2311_p0 = ret_V_40_fu_2311_p00;

assign ret_V_40_fu_2311_p00 = r_V_40_fu_2294_p4;

assign ret_V_41_fu_2338_p0 = ret_V_41_fu_2338_p00;

assign ret_V_41_fu_2338_p00 = r_V_41_fu_2321_p4;

assign ret_V_42_fu_2365_p0 = ret_V_42_fu_2365_p00;

assign ret_V_42_fu_2365_p00 = r_V_42_fu_2348_p4;

assign ret_V_43_fu_2392_p0 = ret_V_43_fu_2392_p00;

assign ret_V_43_fu_2392_p00 = r_V_43_fu_2375_p4;

assign ret_V_44_fu_2419_p0 = ret_V_44_fu_2419_p00;

assign ret_V_44_fu_2419_p00 = r_V_44_fu_2402_p4;

assign ret_V_45_fu_2446_p0 = ret_V_45_fu_2446_p00;

assign ret_V_45_fu_2446_p00 = r_V_45_fu_2429_p4;

assign ret_V_46_fu_2473_p0 = ret_V_46_fu_2473_p00;

assign ret_V_46_fu_2473_p00 = r_V_46_fu_2456_p4;

assign ret_V_47_fu_2500_p0 = ret_V_47_fu_2500_p00;

assign ret_V_47_fu_2500_p00 = r_V_47_fu_2483_p4;

assign ret_V_48_fu_2527_p0 = ret_V_48_fu_2527_p00;

assign ret_V_48_fu_2527_p00 = r_V_48_fu_2510_p4;

assign ret_V_49_fu_2554_p0 = ret_V_49_fu_2554_p00;

assign ret_V_49_fu_2554_p00 = r_V_49_fu_2537_p4;

assign ret_V_4_fu_1339_p0 = ret_V_4_fu_1339_p00;

assign ret_V_4_fu_1339_p00 = r_V_4_fu_1322_p4;

assign ret_V_50_fu_2581_p0 = ret_V_50_fu_2581_p00;

assign ret_V_50_fu_2581_p00 = r_V_50_fu_2564_p4;

assign ret_V_51_fu_2608_p0 = ret_V_51_fu_2608_p00;

assign ret_V_51_fu_2608_p00 = r_V_51_fu_2591_p4;

assign ret_V_52_fu_2635_p0 = ret_V_52_fu_2635_p00;

assign ret_V_52_fu_2635_p00 = r_V_52_fu_2618_p4;

assign ret_V_53_fu_2662_p0 = ret_V_53_fu_2662_p00;

assign ret_V_53_fu_2662_p00 = r_V_53_fu_2645_p4;

assign ret_V_54_fu_2689_p0 = ret_V_54_fu_2689_p00;

assign ret_V_54_fu_2689_p00 = r_V_54_fu_2672_p4;

assign ret_V_55_fu_2716_p0 = ret_V_55_fu_2716_p00;

assign ret_V_55_fu_2716_p00 = r_V_55_fu_2699_p4;

assign ret_V_56_fu_2743_p0 = ret_V_56_fu_2743_p00;

assign ret_V_56_fu_2743_p00 = r_V_56_fu_2726_p4;

assign ret_V_57_fu_2770_p0 = ret_V_57_fu_2770_p00;

assign ret_V_57_fu_2770_p00 = r_V_57_fu_2753_p4;

assign ret_V_58_fu_2797_p0 = ret_V_58_fu_2797_p00;

assign ret_V_58_fu_2797_p00 = r_V_58_fu_2780_p4;

assign ret_V_59_fu_2824_p0 = ret_V_59_fu_2824_p00;

assign ret_V_59_fu_2824_p00 = r_V_59_fu_2807_p4;

assign ret_V_5_fu_1366_p0 = ret_V_5_fu_1366_p00;

assign ret_V_5_fu_1366_p00 = r_V_5_fu_1349_p4;

assign ret_V_60_fu_2851_p0 = ret_V_60_fu_2851_p00;

assign ret_V_60_fu_2851_p00 = r_V_60_fu_2834_p4;

assign ret_V_61_fu_2878_p0 = ret_V_61_fu_2878_p00;

assign ret_V_61_fu_2878_p00 = r_V_61_fu_2861_p4;

assign ret_V_62_fu_2905_p0 = ret_V_62_fu_2905_p00;

assign ret_V_62_fu_2905_p00 = r_V_62_fu_2888_p4;

assign ret_V_63_fu_2932_p0 = ret_V_63_fu_2932_p00;

assign ret_V_63_fu_2932_p00 = r_V_63_fu_2915_p4;

assign ret_V_6_fu_1393_p0 = ret_V_6_fu_1393_p00;

assign ret_V_6_fu_1393_p00 = r_V_6_fu_1376_p4;

assign ret_V_7_fu_1420_p0 = ret_V_7_fu_1420_p00;

assign ret_V_7_fu_1420_p00 = r_V_7_fu_1403_p4;

assign ret_V_8_fu_1447_p0 = ret_V_8_fu_1447_p00;

assign ret_V_8_fu_1447_p00 = r_V_8_fu_1430_p4;

assign ret_V_9_fu_1474_p0 = ret_V_9_fu_1474_p00;

assign ret_V_9_fu_1474_p00 = r_V_9_fu_1457_p4;

assign ret_V_fu_1231_p0 = ret_V_fu_1231_p00;

assign ret_V_fu_1231_p00 = r_V_fu_1220_p1;

assign sext_ln628_10_fu_1507_p1 = ret_V_10_fu_1501_p2;

assign sext_ln628_11_fu_1534_p1 = ret_V_11_fu_1528_p2;

assign sext_ln628_12_fu_1561_p1 = ret_V_12_fu_1555_p2;

assign sext_ln628_13_fu_1588_p1 = ret_V_13_fu_1582_p2;

assign sext_ln628_14_fu_1615_p1 = ret_V_14_fu_1609_p2;

assign sext_ln628_15_fu_1642_p1 = ret_V_15_fu_1636_p2;

assign sext_ln628_16_fu_1669_p1 = ret_V_16_fu_1663_p2;

assign sext_ln628_17_fu_1696_p1 = ret_V_17_fu_1690_p2;

assign sext_ln628_18_fu_1723_p1 = ret_V_18_fu_1717_p2;

assign sext_ln628_19_fu_1750_p1 = ret_V_19_fu_1744_p2;

assign sext_ln628_1_fu_1264_p1 = ret_V_1_fu_1258_p2;

assign sext_ln628_20_fu_1777_p1 = ret_V_20_fu_1771_p2;

assign sext_ln628_21_fu_1804_p1 = ret_V_21_fu_1798_p2;

assign sext_ln628_22_fu_1831_p1 = ret_V_22_fu_1825_p2;

assign sext_ln628_23_fu_1858_p1 = ret_V_23_fu_1852_p2;

assign sext_ln628_24_fu_1885_p1 = ret_V_24_fu_1879_p2;

assign sext_ln628_25_fu_1912_p1 = ret_V_25_fu_1906_p2;

assign sext_ln628_26_fu_1939_p1 = ret_V_26_fu_1933_p2;

assign sext_ln628_27_fu_1966_p1 = ret_V_27_fu_1960_p2;

assign sext_ln628_28_fu_1993_p1 = ret_V_28_fu_1987_p2;

assign sext_ln628_29_fu_2020_p1 = ret_V_29_fu_2014_p2;

assign sext_ln628_2_fu_1291_p1 = ret_V_2_fu_1285_p2;

assign sext_ln628_30_fu_2047_p1 = ret_V_30_fu_2041_p2;

assign sext_ln628_31_fu_2074_p1 = ret_V_31_fu_2068_p2;

assign sext_ln628_32_fu_2101_p1 = ret_V_32_fu_2095_p2;

assign sext_ln628_33_fu_2128_p1 = ret_V_33_fu_2122_p2;

assign sext_ln628_34_fu_2155_p1 = ret_V_34_fu_2149_p2;

assign sext_ln628_35_fu_2182_p1 = ret_V_35_fu_2176_p2;

assign sext_ln628_36_fu_2209_p1 = ret_V_36_fu_2203_p2;

assign sext_ln628_37_fu_2236_p1 = ret_V_37_fu_2230_p2;

assign sext_ln628_38_fu_2263_p1 = ret_V_38_fu_2257_p2;

assign sext_ln628_39_fu_2290_p1 = ret_V_39_fu_2284_p2;

assign sext_ln628_3_fu_1318_p1 = ret_V_3_fu_1312_p2;

assign sext_ln628_40_fu_2317_p1 = ret_V_40_fu_2311_p2;

assign sext_ln628_41_fu_2344_p1 = ret_V_41_fu_2338_p2;

assign sext_ln628_42_fu_2371_p1 = ret_V_42_fu_2365_p2;

assign sext_ln628_43_fu_2398_p1 = ret_V_43_fu_2392_p2;

assign sext_ln628_44_fu_2425_p1 = ret_V_44_fu_2419_p2;

assign sext_ln628_45_fu_2452_p1 = ret_V_45_fu_2446_p2;

assign sext_ln628_46_fu_2479_p1 = ret_V_46_fu_2473_p2;

assign sext_ln628_47_fu_2506_p1 = ret_V_47_fu_2500_p2;

assign sext_ln628_48_fu_2533_p1 = ret_V_48_fu_2527_p2;

assign sext_ln628_49_fu_2560_p1 = ret_V_49_fu_2554_p2;

assign sext_ln628_4_fu_1345_p1 = ret_V_4_fu_1339_p2;

assign sext_ln628_50_fu_2587_p1 = ret_V_50_fu_2581_p2;

assign sext_ln628_51_fu_2614_p1 = ret_V_51_fu_2608_p2;

assign sext_ln628_52_fu_2641_p1 = ret_V_52_fu_2635_p2;

assign sext_ln628_53_fu_2668_p1 = ret_V_53_fu_2662_p2;

assign sext_ln628_54_fu_2695_p1 = ret_V_54_fu_2689_p2;

assign sext_ln628_55_fu_2722_p1 = ret_V_55_fu_2716_p2;

assign sext_ln628_56_fu_2749_p1 = ret_V_56_fu_2743_p2;

assign sext_ln628_57_fu_2776_p1 = ret_V_57_fu_2770_p2;

assign sext_ln628_58_fu_2803_p1 = ret_V_58_fu_2797_p2;

assign sext_ln628_59_fu_2830_p1 = ret_V_59_fu_2824_p2;

assign sext_ln628_5_fu_1372_p1 = ret_V_5_fu_1366_p2;

assign sext_ln628_60_fu_2857_p1 = ret_V_60_fu_2851_p2;

assign sext_ln628_61_fu_2884_p1 = ret_V_61_fu_2878_p2;

assign sext_ln628_62_fu_2911_p1 = ret_V_62_fu_2905_p2;

assign sext_ln628_6_fu_1399_p1 = ret_V_6_fu_1393_p2;

assign sext_ln628_7_fu_1426_p1 = ret_V_7_fu_1420_p2;

assign sext_ln628_8_fu_1453_p1 = ret_V_8_fu_1447_p2;

assign sext_ln628_9_fu_1480_p1 = ret_V_9_fu_1474_p2;

assign sext_ln628_fu_1237_p1 = ret_V_fu_1231_p2;

assign sext_ln840_10_fu_3026_p1 = $signed(add_ln840_10_fu_3020_p2);

assign sext_ln840_11_fu_3036_p1 = $signed(add_ln840_11_fu_3030_p2);

assign sext_ln840_12_fu_3379_p1 = $signed(add_ln840_12_reg_3935);

assign sext_ln840_13_fu_3052_p1 = $signed(add_ln840_15_fu_3046_p2);

assign sext_ln840_14_fu_3062_p1 = $signed(add_ln840_16_fu_3056_p2);

assign sext_ln840_15_fu_3394_p1 = $signed(add_ln840_17_reg_3940);

assign sext_ln840_16_fu_3078_p1 = $signed(add_ln840_18_fu_3072_p2);

assign sext_ln840_17_fu_3088_p1 = $signed(add_ln840_19_fu_3082_p2);

assign sext_ln840_18_fu_3397_p1 = $signed(add_ln840_20_reg_3945);

assign sext_ln840_19_fu_3104_p1 = $signed(add_ln840_22_fu_3098_p2);

assign sext_ln840_1_fu_2948_p1 = $signed(add_ln840_fu_2942_p2);

assign sext_ln840_20_fu_3114_p1 = $signed(add_ln840_23_fu_3108_p2);

assign sext_ln840_21_fu_3406_p1 = $signed(add_ln840_24_reg_3950);

assign sext_ln840_22_fu_3130_p1 = $signed(add_ln840_25_fu_3124_p2);

assign sext_ln840_23_fu_3140_p1 = $signed(add_ln840_26_fu_3134_p2);

assign sext_ln840_24_fu_3409_p1 = $signed(add_ln840_27_reg_3955);

assign sext_ln840_25_fu_3156_p1 = $signed(add_ln840_31_fu_3150_p2);

assign sext_ln840_26_fu_3166_p1 = $signed(add_ln840_32_fu_3160_p2);

assign sext_ln840_27_fu_3424_p1 = $signed(add_ln840_33_reg_3960);

assign sext_ln840_28_fu_3182_p1 = $signed(add_ln840_34_fu_3176_p2);

assign sext_ln840_29_fu_3192_p1 = $signed(add_ln840_35_fu_3186_p2);

assign sext_ln840_2_fu_2958_p1 = $signed(add_ln840_1_fu_2952_p2);

assign sext_ln840_30_fu_3427_p1 = $signed(add_ln840_36_reg_3965);

assign sext_ln840_31_fu_3208_p1 = $signed(add_ln840_38_fu_3202_p2);

assign sext_ln840_32_fu_3218_p1 = $signed(add_ln840_39_fu_3212_p2);

assign sext_ln840_33_fu_3436_p1 = $signed(add_ln840_40_reg_3970);

assign sext_ln840_34_fu_3234_p1 = $signed(add_ln840_41_fu_3228_p2);

assign sext_ln840_35_fu_3244_p1 = $signed(add_ln840_42_fu_3238_p2);

assign sext_ln840_36_fu_3439_p1 = $signed(add_ln840_43_reg_3975);

assign sext_ln840_37_fu_3260_p1 = $signed(add_ln840_46_fu_3254_p2);

assign sext_ln840_38_fu_3270_p1 = $signed(add_ln840_47_fu_3264_p2);

assign sext_ln840_39_fu_3448_p1 = $signed(add_ln840_48_reg_3980);

assign sext_ln840_3_fu_3364_p1 = $signed(add_ln840_2_reg_3920);

assign sext_ln840_40_fu_3286_p1 = $signed(add_ln840_49_fu_3280_p2);

assign sext_ln840_41_fu_3296_p1 = $signed(add_ln840_50_fu_3290_p2);

assign sext_ln840_42_fu_3451_p1 = $signed(add_ln840_51_reg_3985);

assign sext_ln840_43_fu_3312_p1 = $signed(add_ln840_53_fu_3306_p2);

assign sext_ln840_44_fu_3322_p1 = $signed(add_ln840_54_fu_3316_p2);

assign sext_ln840_45_fu_3460_p1 = $signed(add_ln840_55_reg_3990);

assign sext_ln840_46_fu_3338_p1 = $signed(add_ln840_56_fu_3332_p2);

assign sext_ln840_47_fu_3348_p1 = $signed(add_ln840_57_fu_3342_p2);

assign sext_ln840_48_fu_3463_p1 = $signed(add_ln840_58_reg_3995);

assign sext_ln840_4_fu_2974_p1 = $signed(add_ln840_3_fu_2968_p2);

assign sext_ln840_5_fu_2984_p1 = $signed(add_ln840_4_fu_2978_p2);

assign sext_ln840_6_fu_3367_p1 = $signed(add_ln840_5_reg_3925);

assign sext_ln840_7_fu_3000_p1 = $signed(add_ln840_7_fu_2994_p2);

assign sext_ln840_8_fu_3010_p1 = $signed(add_ln840_8_fu_3004_p2);

assign sext_ln840_9_fu_3376_p1 = $signed(add_ln840_9_reg_3930);

assign sext_ln840_fu_2938_p1 = ret_V_63_fu_2932_p2;

assign xor_ln1039_1_fu_3541_p2 = (icmp_ln1039_2_fu_3536_p2 ^ 1'd1);

assign xor_ln1039_fu_3523_p2 = (icmp_ln1039_1_fu_3518_p2 ^ 1'd1);

assign zext_ln1039_1_fu_3515_p1 = p_ZL7threshs_1_load_reg_4045_pp0_iter3_reg;

assign zext_ln1039_2_fu_3533_p1 = p_ZL7threshs_2_load_reg_4050_pp0_iter3_reg;

assign zext_ln1039_fu_3497_p1 = p_ZL7threshs_0_load_reg_4040_pp0_iter3_reg;

assign zext_ln840_1_fu_3547_p1 = xor_ln1039_1_fu_3541_p2;

assign zext_ln840_2_fu_3511_p1 = result_V_fu_3505_p2;

assign zext_ln840_fu_3529_p1 = xor_ln1039_fu_3523_p2;

endmodule //MVAU_hls_2_Matrix_Vector_Activate_Stream_Batch
