from utils.cli_logger import Logger
from models.models import single_layer
from utils.pruning import analyze_model_sparsity, global_magnitude_prune_with_min
from utils.export_ip import finn_export_ip, finn_export_onnx
from qonnx.core.datatype import DataType
import finn.builder.build_dataflow_config as build_cfg

# set random seed for reproducibility
import torch
import json
import re
from datetime import datetime
torch.manual_seed(1998)    

FPS_MAX = 10000000000
FPS_MIN = 1

def mvau_ablation_test(ablation_name="a0_mvau_ablation",
                       calculation_size=64,
                        sparsity=0.9,
                         strategy_no=1,
                          target_fps=1,
                          ):
     
    if strategy_no == 0:
        strategy = build_cfg.dense_dataflow_steps
    elif strategy_no == 1:
        strategy = build_cfg.spmv_only_dataflow_steps
    elif strategy_no == 2:
        strategy = build_cfg.lutsp_only_dataflow_steps
    elif strategy_no == 3:
        strategy = build_cfg.hybridsp_dataflow_steps  
    else:
        strategy = build_cfg.dense_dataflow_steps

    test_name = f"""size{calculation_size}_sp{int(sparsity*100)}_s{strategy_no}_fps{target_fps}"""
    log_dir = f"logs/ablation/{ablation_name}"
    log_name = f"{test_name}.log"
    logger = Logger(filename=log_name, log_dir=log_dir)
    start_time = datetime.now()
    logger.log(f"Starting MVAU ablation test at {start_time.strftime('%Y-%m-%d %H:%M:%S')}...")
    model = single_layer(w=2, a=2, size=calculation_size)
    logger.log(f"Model created: {model}")
    sparsity_info = analyze_model_sparsity(model)
    logger.log(f"Sparsity analysis: {sparsity_info}")
    pruned_model = global_magnitude_prune_with_min(model, target_sparsity=sparsity)
    logger.log(f"Pruned model: {pruned_model}")
    pruned_sparsity_info = analyze_model_sparsity(pruned_model)
    logger.log(f"Pruned model sparsity analysis: {pruned_sparsity_info}")
    # print the weights after pruning

    for name, param in pruned_model.named_parameters():
        if 'weight' in name:
            logger.log(f"Weights of {name} after pruning: {param.data}")

    finn_export_onnx(pruned_model.cpu(),
                      output_onnx_path=f"models/ablation/{ablation_name}/onnx/{test_name}_pruned.onnx",
                       input_shape=(1, calculation_size),
                        input_datatype=DataType["INT2"],
                         output_datatype=DataType["INT2"])
    finn_export_ip(f"models/ablation/{ablation_name}/onnx/{test_name}_pruned.onnx",
                    output_dir=f"models/ablation/{ablation_name}/{test_name}_pruned_ip",
                     mvau_wwidth_max=10000,
                      target_fps=target_fps, # MAX
                        synth_clk_period_ns=10.0,
                            fpga_part="xczu7ev-ffvc1156-2-e", # Target ZCU 104
                             steps = strategy)


    logger.log(f"loading performance reports...")
    # extract performance from the log file generated by finn_export_ip
    rtl_report = f"models/ablation/{ablation_name}/{test_name}_pruned_ip/report/rtlsim_performance.json"
    ooc_report = f"models/ablation/{ablation_name}/{test_name}_pruned_ip/report/ooc_synth_and_timing.json"
    folding_report = f"models/ablation/{ablation_name}/{test_name}_pruned_ip/auto_folding_config.json"
    power_report = f"models/ablation/{ablation_name}/{test_name}_pruned_ip/build_dataflow.log"

    # open rtl report
    with open(rtl_report, "r") as f:
        rtl_data = json.load(f)
    cycles = round(rtl_data["cycles"], 2)
    # open ooc report
    with open(ooc_report, "r") as f:
        ooc_data = json.load(f)
    fmax_mhz = round(ooc_data["fmax_mhz"], 2)
    fps = round(ooc_data["estimated_throughput_fps"], 2)
    lut = round(ooc_data["LUT"], 2)
    # open folding report
    with open(folding_report, "r") as f:
        folding_data = json.load(f)
    pe = folding_data["MVAU_hls_0"]['PE']
    simd = folding_data["MVAU_hls_0"]['SIMD']
    # open power report
    # with open(power_report, "r") as f:
    #     for line in f:
    #         match = re.search(r"finn_design_wrapper\s*\|\s*([\d.]+)\s*\|", line)
    #         if match:
    #             power_value = float(match.group(1))
    #             break  

    # if power_value is not None:
    #     power = round(power_value, 5)
    # else:
    #     power = 0.0
    #     print("Power value not found in log.")
    power = 0.0  # Placeholder for power value

    logger.log(f"Performance report for {test_name}:")
    logger.log(f"Cycles: {cycles}")
    logger.log(f"Fmax (MHz): {fmax_mhz}")
    logger.log(f"FPS: {fps}")
    logger.log(f"LUTs: {lut}")
    logger.log(f"PE: {pe}")
    logger.log(f"SIMD: {simd}")
    logger.log(f"Power (W): {power}")

    end_time = datetime.now()
    runtime = end_time - start_time
    total_seconds = int(runtime.total_seconds())
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    logger.log(f"{'St':<5}{'Sp':<5}{'M':<5}{'Latency (us)':<15}{'LUTs':<10}{'Power (W)':<12}{'Cycles':<10}{'Fmax (MHz)':<12}{'Throughput':<15}{'Target FPS':<12}")
    logger.log("-" * 100)

    latency_us = (cycles / fmax_mhz) if fmax_mhz > 0 else 0

    logger.log(f"{strategy_no:<5}{sparsity:<5}{calculation_size:<5}{latency_us:<15.2f}{lut:<10}{power:<12.4f}{cycles:<10}{fmax_mhz:<12.2f}{fps:<15.2f}{target_fps:<12.2f}")
    logger.log(f"MVAU ablation test completed at {end_time.strftime('%Y-%m-%d %H:%M:%S')}.")
    logger.log(f"runtime: {hours}h, {minutes}min, {seconds}s")

    logger.log(f"log saved to {log_dir}/{log_name}")

if __name__ == "__main__":
    # ablation test 3
    # 3.1 spmv
    # 800000: 4, 1
    # 1600000: 8, 1
    # 25600000: 16, 8
    # sparsity_list = [0.1, 0.3, 0.5, 0.7, 0.9]
    # fps_list = [1, 800000, 1600000, 25600000]
    # strategy = 1
    # Matrix_size = 16

    # for sparsity in sparsity_list:
    #     for target_fps in fps_list:
    #         mvau_ablation_test(ablation_name="a2_mvau_ablation",
    #                 calculation_size=Matrix_size,
    #                 sparsity=sparsity,
    #                     strategy_no=strategy,
    #                     target_fps=target_fps)
    # # 3.2 dense
    # sparsity = 0.9
    # fps_list = [1, 800000, 1600000, 25600000]
    # strategy = 0
    # Matrix_size = 16

    # for target_fps in fps_list:
    #     mvau_ablation_test(ablation_name="a2_mvau_ablation",
    #             calculation_size=Matrix_size,
    #             sparsity=sparsity,
    #                 strategy_no=strategy,
    #                 target_fps=target_fps)
    sparsity_list = [0.1, 0.3, 0.5, 0.7, 0.9]
    fps_list = [400000]
    strategy = 1
    Matrix_size = 16

    for sparsity in sparsity_list:
        for target_fps in fps_list:
            mvau_ablation_test(ablation_name="a2_1_mvau_ablation",
                    calculation_size=Matrix_size,
                    sparsity=sparsity,
                        strategy_no=strategy,
                        target_fps=target_fps)
    # 3.2 dense
    sparsity = 0.9
    fps_list = [400000]
    strategy = 0
    Matrix_size = 16

    for target_fps in fps_list:
        mvau_ablation_test(ablation_name="a2_1_mvau_ablation",
                calculation_size=Matrix_size,
                sparsity=sparsity,
                    strategy_no=strategy,
                    target_fps=target_fps)